### ISSUE TITLE
Re: EVCloudKitDao.publicDB.query method

### ISSUE THREAD

**Issue by yoonack** [evermeer/EVCloudKitDao#11]
Hi,

I am currently trying to query a record with NSPredicate(format: "field BEGINSWITH %@", searchfield), I notice that the code inside the completion block is run with a noticeable delay. I used connect method before with different NSPredicate, but the result is pretty fast. I am wondering, if I just use the query method directly, would it slow down the completion block execution, or is it because of the NSPredicate type?

**Comment by evermeer** [comment]
I have just done some test. For this I added some extra logging into the EVCloudKitDao queryRecords method. That is the method that handles all queries. what I added was:
```
        NSLog("execute operation")
        database.addOperation(operation)
        NSLog("ready execute operation")
```
I run the app demo and went to the search menu item. That one will do a BEGINSWITH query. The demo also logs when a you start a query and when the result is returned. In all cases The 3 log statements up til the 'ready execute operation' where within 2 milliseconds. And then the result was returned somewhere between 0.7 and 1.2 seconds. Here is a snippet of the log:
```
06/07/2015 09:45:11:111 AppMessage)[1554:.] SearchViewController.swift(61) filterContentForSearchTextV2:
	Filter for u
2015-06-07 09:45:11.112 AppMessage[1554:15438] execute operation
2015-06-07 09:45:11.112 AppMessage[1554:15438] ready execute operation
06/07/2015 09:45:11:866 AppMessage)[1554:.] SearchViewController.swift(64) filterContentForSearchTextV2:
	query for tokens 'u' result count = 1
```
When doing another query I did not notice any big differences. For instance querying all messages for the To field resulted in this log:
```
2015-06-07 09:51:47.035 AppMessage[1554:15438] execute operation
2015-06-07 09:51:47.035 AppMessage[1554:15438] ready execute operation
06/07/2015 09:51:49:161 AppMessage)[1554:.] ChatViewController.swift(102) initializeCommunication():
	Conversation message results = 100
```
That one even took 2 seconds to execute. But that could be the 100 records that It had to return.

I guess the type of query could influence how fast you would get a return. I haven't seen any documentation or tests about the performance of CloudKit.

One other thing... The .conect method will use local cashing for a predicate. So if you execute a .connect for the 2nd time, it will first return the results of whatever is in cache and then execute the actual query. The moment the data is returned from CloudKit and there was a chage, you will get a 2nd callback with the new result. So indeed in some situations it might look like the .conect method will return instantly. If you do not want this caching, then call the .connect using CachingStrategy.None

**Comment by yoonack** [comment]
Thanks a lot for the test. This is great. How about if I want to query a field that contains a certain string, what NSPredicate should I use? I thought about the "self contains "string"" predicate, but it would search all the field. I just want to match a certain field. 

I really appreciate your help!

**Comment by yoonack** [comment]
One thing I also notice, in my query, I called these method: 
self.checkAttachedAssets(results)
                self.loadingView.activityViewAnimated(false)
                self.tableView.reloadData()
the loadingVIew is just trying to stop the activityIndicator. However, the result is returned with very fast time, but these blocks are called with around 4 seconds delay, I have no idea what caused that performance.

**Comment by evermeer** [comment]
Sorry, there is no such query (yet). You can only do a beginswith or a tokenized search. Another big miss is that you cannot do an OR query. 

The only workaround in your case that I can think of is creating an extra recordType with only the field that you want to query (duplicated data) plus a CKReference to the original record and do a tokenized search on that new recordType. After that you have to query your original recordType for all the referenced records.

Are you fetching data using EVCloudKitDao or EVCloudData? Only EVCloudData performs all callbacks on the main thread. EVCloudKitDao performs the callbacks on the background thread. So If you use that and want to update any UI, you also have to do a call to the main thread. Otherwise you will indeed see strange timing results (or even crashes). You can use a code block like:
```
     NSOperationQueue.mainQueue().addOperationWithBlock {
         ....
     }
```

**Comment by yoonack** [comment]
Yeah, originally I was thinking of creating another record type only contains the query field. However, since I have to display the original record data, it would just save time and transfer data for querying original record. 

I am using EVCloudKitDao to do the querying. No wonder I see the delay on the callback. I will try the other option. Thanks for the reply!
