### ISSUE TITLE
EVCloudKitDao.getItem, a segment should expect an optional value, not unwrapped value

### ISSUE THREAD

**Issue by InfiniteRandomVariable** [evermeer/EVCloudKitDao#12]
Please see this function below for reference. 

database.fetchRecordWithID returns an optional value from "record" in the completionHandler. 
In the following segment, this function, "self.fromCKRecord(record)", doesn't accept optional value. Will crash if the record is nil value.

Hope it helps.
Thanks for your comment here 
http://stackoverflow.com/questions/30726681/find-user-name-or-first-last-name-in-ios9-cloudkit-abperson-abaddressbook/30816414#30816414
K.

My fix:
..
database.fetchRecordWithID(CKRecordID(recordName: recordId), completionHandler: { (record: CKRecord?, error: NSError?) in
..

Reference:
    public func getItem(recordId: String, completionHandler: (result: EVCloudKitDataObject) -> Void, errorHandler:((error: NSError) -> Void)? = nil) {
        database.fetchRecordWithID(CKRecordID(recordName: recordId), completionHandler: {record, error in
            self.handleCallback(error, errorHandler: errorHandler, completionHandler: {
                if let parsed = self.fromCKRecord(record) {
                    completionHandler(result: parsed);

**Comment by evermeer** [comment]
Strange... As you can see, the .fromCKRecord is within the .handleCallback block. The completionHandler will only be called if error was nil. You are right that there will be a crash if both are nil.  I assumed this was not possible. If you don't get a record you should have an error right? 
I will apply your fix later today. Thanks for noticing this and reporting it in such detail!

**Comment by evermeer** [comment]
I just pushed version 2.5.0 to github with a fix for your issue.
