### ISSUE TITLE
Write Operation Not Permitted?

### ISSUE THREAD

**Issue by yoonack** [evermeer/EVCloudKitDao#13]
Hi,

I am trying to modify the record as another user and save the modified record. However, iCloud is giving me this error message:" server message = \"WRITE operation not permitted\"

Does that mean I cant modify the record created by other user? Thanks

**Comment by evermeer** [comment]
In CloudKit dashboard you can configure the permissions on a recordType. By default a record can only be modified by the user that created it. If you want every user to be able to change data, then just change the permissions on that recordType

**Comment by yoonack** [comment]
Oh, great, I just found it out too. By the way, I cant see the data that being modified by other user in the Cloudkit dashboard?

**Comment by evermeer** [comment]
Not if you are writing to the private database. The public database will have the data of all users

**Comment by yoonack** [comment]
I am writing to the public database with the data that contains the userRecordID.recordName of the current user. I can't view the data with the main user. However, when I query it, it actually comes back the data being written.

**Comment by evermeer** [comment]
The standard permissions for read is public. So you should be able to see the data of everyone. Are you sure you are looking to the same container? What happens if you modify data in the CloudKit dashboard, are you able to read that back in your app?
