### ISSUE TITLE
Data Modification notification

### ISSUE THREAD

**Issue by yoonack** [evermeer/EVCloudKitDao#14]
I am trying to use the connect method to create the subscription handler. The insert handler is working fine when there is data being added. However, when I modify the existing data created by another user, and save it the icloud, the original user doesn't receive the update notification. Do you know how should I deal with such situation?

**Comment by evermeer** [comment]
You are probably doing it right. There are some CloudKit problems with update notifications. See:
http://stackoverflow.com/questions/31199667/cloudkit-subscriptions-for-cksubscriptionoptionsfiresonrecordupdate-not-working

**Comment by evermeer** [comment]
Closing this issue since it's a CloudKit bug and not an EVCloudKitDao bug

**Comment by InfiniteRandomVariable** [comment]
This seems like deal breaker for using Cloudkit. Does this kind of problems happen often?

**Comment by evermeer** [comment]
Well, there are more bugs. Like the CloudKit badge reset still not working. I created a workaround for this issue. I created an update table where i insert a new record that has a ckreference to the updated record. It's an insert so you will get a notification for it. That table can then be purged on a regular basis.

**Comment by InfiniteRandomVariable** [comment]
One main upside is their support of seemingly online modifying existing iCloud DB schema. However, from User Experience first point of view, they should never mess up with the Production backhand.
