### ISSUE TITLE
Swift 2.0 / Xcode-7 compatibility

### ISSUE THREAD

**Issue by appsird** [evermeer/EVCloudKitDao#15]
Is the recent release Xcode 7-beta-5 / iOS9 / Swift 2.0 compatible?

**Comment by evermeer** [comment]
For that you have to use the swift2 branch. It's tested with Xcode 7 beta 5.
You can use that branch by putting the following line in your podfile:
pod 'EVCloudKitDao', :git => 'https://github.com/evermeer/EVCloudKitDao.git', :branch => 'swift2'

when Xcode 7 is out of beta I will create a branch of the current trunk called swift1.2 and merge the swift2 branch to the trunk
