### ISSUE TITLE
Swift 2.0 issue

### ISSUE THREAD

**Issue by gloparco** [evermeer/EVCloudKitDao#16]
Hey Edwin, fantastic work on this library!  I have learned a lot from it... I did not want the reflection mapping, so I ended up borrowing bits and pieces from your lib, but now that I have done so, I wish I had just taken the whole thing! :-)

Anyway, this isn't really an issue with your code, so much as a Swift language change with v2.0.  I noticed that you can no longer specify binary operators as such (see: http://stackoverflow.com/questions/30761996/swift-2-0-binary-operator-cannot-be-applied-to-two-uiusernotificationtype):

    var subscription = CKSubscription(recordType: recordType, predicate: predicate, subscriptionID:key, options: .FiresOnRecordCreation | .FiresOnRecordUpdate | .FiresOnRecordDeletion)

Instead, I believe the way to do it now, is as so:

    var subscription = CKSubscription(recordType: recordType, predicate: predicate, subscriptionID:key, options: [.FiresOnRecordCreation, .FiresOnRecordUpdate, .FiresOnRecordDeletion])

Hope this helps!

-Gene

**Comment by evermeer** [comment]
Thanks Gene,

I was using this in the swift 2 branch:
```
... options: CKSubscriptionOptions(rawValue:CKSubscriptionOptions.FiresOnRecordCreation.rawValue + CKSubscriptionOptions.FiresOnRecordUpdate.rawValue + CKSubscriptionOptions.FiresOnRecordDeletion.rawValue)
```

Which also works, but how you do it is cleaner. So I changed it to that.

... Edwin
