### ISSUE TITLE
Saving to cache

### ISSUE THREAD

**Issue by just-a-beginner** [evermeer/EVCloudKitDao#17]
Hey EV! Your library here is really amazing, thank you so much for your hard work on it.

I have a couple of (probably stupid) questions about when you cache data. I have looked through the docs and I'm not seeing all the details about how it is caching... 

1 - Is it saving a file to NSUserDefaults? I'm assuming the cache persists on app launch/close. 
2 - I know EVCloudKitDao will be able to view/edit/save this data, but I am wondering what kind of format this file is in. (I'm hoping to avoid having to set up Core Data to interface with CloudKit)
3 - Can you explain what I can expect if the user launches the app without internet, but with a local cache saved?

Thanks! I'm a beginner so I appreciate your patience :)

**Comment by evermeer** [comment]
There are no stupid questions... Only stupid answers :)

The .connect method will save the incoming data to a file (not NSUserDefaults) the moment the data arrives (for any modification). When your app closes and reopens, the moment the same .connect is called again the data will first be returned from that cached file. It will also query CloudKit for the data. If the data is changed, then you will get a second callback with the updated data. 

When there is no internet, then you will get a callback with the data that is read from the file and after that the error callback will be called with an indication what went wrong.

The file is created and read using standard NSCoding support. NSCoding support was added to EVCloudKitDao throught the EVReflection library. (a spin off library of EVCloudKitDao)

If you have any other questions, then don't hesitate to ask.

**Comment by just-a-beginner** [comment]
That really helps - thanks!

If CloudKit contains a CKAsset that was an image (for example) would the cache actually download this image or would it only have a reference to the CKAsset? 

Trying to understand if the entire CloudKit record including the CKAssets should be available in cache. This might affect my programs data usage, so I want to make sure I understand it.

**Comment by evermeer** [comment]
A CKAsset is part of a CKRecord. The file itself will be downloaded, but it will be saved by CloudKit into your temp folder. You do not have to do another fetch for the file. The cashing of that file is managed by CloudKit. So if you want to make sure the file remains available then you have to move them to the documents folder.

**Comment by just-a-beginner** [comment]
Ok, that makes sense. Thank you for being so helpful, I really appreciate it.
