### ISSUE TITLE
Add tvOS 9.0 target

### ISSUE THREAD

**Issue by tbaggett** [evermeer/EVCloudKitDao#18]
Thanks for what looks like an AWESOME library! I'm new to tvOS, Swift, Cocoapods, etc., but I think this should be relatively straightforward. It should just be a matter of adding a target for tvOS 9.0 to the pod config, right?

**Comment by tbaggett** [comment]
I added a pull request with the podfile additions for a tvOS target. Apologies if more is needed to support tvOS.  https://github.com/evermeer/EVCloudKitDao/pull/19

**Comment by evermeer** [comment]
It's now activated in release 2.9.3
