### ISSUE TITLE
___createTime' is not marked sortable

### ISSUE THREAD

**Issue by InfiniteRandomVariable** [evermeer/EVCloudKitDao#2]
Error:
NSLocalizedDescription=Field '___createTime' is not marked sortable}, ErrorDescription: Field '___createTime' is not marked sortable]

CODE
Caused by this statement.
EVCloudKitDao 
query.sortDescriptors = [NSSortDescriptor(key: "creationDate", ascending: false)]

REPRODUCE 
running XCode 6.3 Swift, swift XCTestCase module.
Follow steps similar to the official prescribed methods or this
https://github.com/evermeer/EVCloudKitDao/blob/master/AppMessage/AppMessage/Controlers/TestsViewController.swift. 
Create any new object and wait 10 seconds, query it, it will produce this error. 

They suggest the problem will resolve with time. It isn't my case. 
http://stackoverflow.com/questions/24907319/cloudkit-data-purged-again-and-now-i-cannot-sort-on-creationdate

**Comment by evermeer** [comment]
When a new recordType is created, you need to go to the CloudKit dashboard and make the metadata fields sortable. (select the AppMessage container, select each recordType, check all metadata indexes.

Besides that, I just noticed that the initial record creation line of code was commented out.
In the application didFinishLaunchingWithOptions you can see the following line:
'''
        EVCloudKitDao.publicDB.createRecordTypes([Message(), Asset(), News()])
'''
That line will setup the recordTypes Message Asset and News.

**Comment by InfiniteRandomVariable** [comment]
Right on. Try to jumpstart into iCloud. Previous experience with Parse and custom EC2 Cloud experience can only help little.

**Comment by evermeer** [comment]
Welcome to CloudKit! There are not many CloudKit developers, so everybody that is trying it out is welcome! If you have any questions, then just ask.

When you are OK to stick to Apple, then CloudKit is by far the easiest solution for central data storage and push notifications. (I have tried Parse, Azure and AWS)

**Comment by InfiniteRandomVariable** [comment]
The promise of iCloud should rise with the popularity of the Apple Watch. My Watch App was ready with Parse until I see the AWESOMENESS of CloudKit and your project. Roll back 40% of implementations, happily not looking back.
