### ISSUE TITLE
Message App

### ISSUE THREAD

**Issue by orangecoding** [evermeer/EVCloudKitDao#21]
Hey,

I neither can add contacts to the messaging app, nor is the description correct. (You've stated that I should open the left side menu for contacts where the right side menu says "contacts".

Is this app currently within restructuring?

**Comment by evermeer** [comment]
Ah, I see... It's a grammar thing. It should have said something like:
Welcome to the AppMessage CloudKit demo. Open the menu on the left, or go to Contacts on the right and start a conversation. (It will only show other contacts that also installed the app)

I just updated that text. 

So the only way to see contacts is by installing the app on 2 devices which each a different active iCloud account and both have the other in its contact list.

This contact list is build this way to show how to discover contacts. If you wan to build a real messenger app, then you might want an alternate way to find other contacts. The AppMessage demo is only created to show the possibilities of CloudKit. It's not meant to be a complete messaging app.
