### ISSUE TITLE
How to update iCloud account status when user signs out or changes accounts?

### ISSUE THREAD

**Issue by tbaggett** [evermeer/EVCloudKitDao#22]
Is there currently a way to force the public/private db's accountStatus property to be updated when a NSUbiquityIdentityDidChangeNotification is received or when the app becomes active and a change in the iCloud account status is detected by inspecting the NSFileManager.defaultManager().ubiquityIdentityToken?

**Comment by evermeer** [comment]
It looks like you need to re-initiate the container and database. Currently EVCloudKitDao does not have a separate function for that. I will now move the code from the init to a new public function for that. I will push that version later today to GitHub.

**Comment by evermeer** [comment]
You will be able to reinitialize the database using:
EVCloudKitDao.publicDb.initializeDatabase()
This also works on the privateDb and you can pass a containerId as a parameter.
You also need to call the .discoverUserInfo if you want to get the new userId.

**Comment by tbaggett** [comment]
Awesome! Thanks as always for the quick response and update.
