### ISSUE TITLE
tvOS returns unexpected nil CKDiscoveredUserInfo value in discoverUserInfo(...)

### ISSUE THREAD

**Issue by tbaggett** [evermeer/EVCloudKitDao#24]
Testing on current beta releases of Xcode (7.2 Beta 3) and tvOS (9.1 Beta 2) on both the simulator and an Apple TV device against my iCloud development environment. 

Attempting to retrieve signed-in iCloud user's first and last name by calling the EVCloudKitDao.privateDB.discoverUserInfo() method.

CloudKit is returning a nil value for the user. Line 421, where an attempt to call the provided completion handler, causes an exception when an attempt is made to unwrap the nil value. I verified that a non-nil recordID was returned. Any idea why no user information is being returned?

I also tried using the publicDB.discoverUserInfo() method and saw the same results.

    public func discoverUserInfo(completionHandler: (user: CKDiscoveredUserInfo) -> Void, errorHandler:((error:NSError) -> Void)? = nil) {
        container.fetchUserRecordIDWithCompletionHandler({recordID, error in
            self.handleCallback(error, errorHandler: errorHandler, completionHandler: {
                self.container.discoverUserInfoWithUserRecordID(recordID!, completionHandler: { user, error in
                    self.handleCallback(error, errorHandler: errorHandler, completionHandler: {
                        self.activeUser = user

                        // no errors were returned by CloudKit but user is nil
                        completionHandler(user: user!)

                    })
                })
            })
        })
    }

**Comment by tbaggett** [comment]
I forgot to mention that I'm not calling EVCloudKitDao.publicDB.requestDiscoverabilityPermission. I'm only interested in getting the user's name for display in the app. Is that call required for fetching the user's name to work as expected?

**Comment by evermeer** [comment]
you should be able to call discoverUserInfo without requestDiscoverabilityPermission. The user should not be nil. When it's nil there should be an error. I assumed that when the error is nil, the user would be populated. Apparently in your situation they are both nil. I will have a look at it to see what we should do in that situation.

**Comment by evermeer** [comment]
I just pushed version 2.11.2 to GitHub
now when a value is required and both the error and value are nil, you will get a custom error.

**Comment by tbaggett** [comment]
Thanks for the update. I will explore why this condition is occurring further and let you know if I find an explanation.

**Comment by tbaggett** [comment]
I think this is occurring because I initially denied the CKApplicationPermissionUserDiscoverability request, as we've discussed before. According to the tvOS CKContainer class reference documentation (https://developer.apple.com/library/tvos/documentation/CloudKit/Reference/CKContainer_class/index.html#//apple_ref/occ/instm/CKContainer/discoverUserInfoWithUserRecordID:completionHandler:), discoverUserInfoWithUserRecordID won't return a CKDiscoveredUserInfo instance unless this permission was granted:

Discussion
Use this method to retrieve information about a user for which you already have a user record ID. The user you are searching for must meet the following criteria:

- The user must have run the app.

- **The user must have granted the CKApplicationPermissionUserDiscoverability permission for this container.**

**Comment by tbaggett** [comment]
Correction: I actually had not denied the request. My account reported it was still in the initial state. I confirmed that I have to grant the permission with the code below.

I was hoping to display "Signed in as First Last" on my document selection screen to give users a clue if their previously-created documents aren't displayed due to someone else being currently logged in. Since the Apple TV is shared by family members, this is a likely possibility. However, I don't want users to be prompted to share their personal information with other users just so I can display their name, so I will be removing that feature.

      let container = CKContainer.defaultContainer()
      container.fetchUserRecordIDWithCompletionHandler { (recordID, error) in
        guard error == nil else { return }
        guard let recordID = recordID else { return }
        
        container.discoverUserInfoWithUserRecordID(recordID) { (info, fetchError) in
          // use info.firstName and info.lastName however you need
          container.statusForApplicationPermission(.UserDiscoverability) { (status, error) in
            if status == .InitialState {
              container.requestApplicationPermission(.UserDiscoverability) { (status, error) in
                EVLog(status)
                EVLog(error)
              }
            }
            EVLog(status)
            EVLog(error)
          }
          EVLog(info)
          EVLog(fetchError)
        }
      }
