### ISSUE TITLE
How to know when query is finished reading from within completionHandler?

### ISSUE THREAD

**Issue by tbaggett** [evermeer/EVCloudKitDao#26]
Hello again, sorry if I'm becoming a pest! And apologies if this is a newb question as well.

I am displaying an activity indicator when I call EVCloudData.privateDB.connect(). I need to stop the activity indicator when my completionHandler is called but I don't see how to know that the query has finished returning results. 

In looking at the source, I see that a cursor is received by the queryCompletionBlock closure and that if the completionHandler returns true and the cursor is not nil, the private queryRecords method is called with the cursor being passed to it to continue retrieving query results.

It seems like passing an "isFinished" boolean value (defined as "cursor == nil") to the completionHandler would be an easy way to handle this if there isn't an existing means of determining this. If this is what is needed, I will be happy to produce a pull request that makes the needed changes to the project.

Thanks as always for your efforts on this project.

**Comment by evermeer** [comment]
That sounds like a good addition. It would be great if you could create a PR for that. Otherwise I will have a look at it later this weekend.

**Comment by tbaggett** [comment]
Great! I will work on that tomorrow (almost 1 AM local time). Thanks.

**Comment by evermeer** [comment]
Here it's now 8 AM. I'm just getting started :)

**Comment by tbaggett** [comment]
Pull request created: https://github.com/evermeer/EVCloudKitDao/pull/28

**Comment by evermeer** [comment]
I just updated the cocoapod to version 2.12.0 instead of 2.11.3 since there are breaking changes in this version (extra parameter in the callback)

**Comment by tbaggett** [comment]
Ok cool, I thought of that after committing, still getting the hang of this, haven't contributed to OSS projects up until the last couple of months. Thanks for catching that and taking care of it.
