### ISSUE TITLE
[Enhancement] Uncaught Time Specific Error in handleCloudKitErrorAs Func

### ISSUE THREAD

**Issue by InfiniteRandomVariable** [evermeer/EVCloudKitDao#27]
Hi Edwin,

If the app accesses iCloud too early, one might experience this error 
```
<CKError 0x16e798a0: "Not Authenticated" (9/1002); "CloudKit access was denied by user settings"; Retry after 3.0 seconds>.
```

This function was partially unable to manage the time specific variable given the return CKError. 
Perhaps adds a special case to the function below like so..
```
public static func handleCloudKitErrorAs(error:NSError?, retryAttempt:Double = 1) -> 
   ...
case .NotAuthenticated .NetworkUnavailable, .NetworkFailure, .ServiceUnavailable, .RequestRateLimited, .ZoneBusy, .ResultsTruncated:
    ...
```
Not aware they mention this in the documentation, the following implementation also support NotAuthenticated in my test.
```
            if let userInfo = error?.userInfo {
                if let retry = userInfo[CKErrorRetryAfterKey] as? NSNumber {
                    seconds = Double(retry)
                }
```
Thanks for the private email addressed my inquiry!

update from @evermeer: I updated the questions. Some info was not rendered.

**Comment by evermeer** [comment]
Ah, I did not know that the 'Not Authenticated" error could be recovered. I will push an update to GitHub in a moment. 

You are right. I should check for the userInfo[CKErrorRetryAfterKey] first and then use that if it's set.

**Comment by evermeer** [comment]
I just pushed version 2.11.3 with this fix.

Thanks again for reporting this!
