### ISSUE TITLE
Swift 1.2 swiftClassFromString always return nil

### ISSUE THREAD

**Issue by InfiniteRandomVariable** [evermeer/EVCloudKitDao#3]
Tried several ways in this thread to little avail. 
http://stackoverflow.com/questions/24030814/swift-language-nsclassfromstring

e.g.
@objc(Messsage)
class Message : EVCloudKitDataObject

Fix:
In EVReflection:
Use objc_getClass(anyobjectTypeString) instead of swiftClassFromString(anyobjectTypeString).

**Comment by evermeer** [comment]
Could you explain a little more what you mean? I just extended the testViewController with the following code:


class xxx:NSObject {
    var y:String = ""
}

class TestsViewController : UIViewController {
    

    @IBAction func runTest(sender: AnyObject) {
        
        
        var z = xxx()
        
        var a:String = EVReflection.swiftStringFromClass(z)
        NSLog("swiftStringFromClass = \(a)")
        
        if var anyobjectype : AnyObject.Type = EVReflection.swiftClassFromString(a) {
            var nsobjectype : NSObject.Type = anyobjectype as! NSObject.Type
            var nsobject: NSObject = nsobjectype()
            NSLog("object = \(nsobject)")
        }

And the result of that is:
2015-04-28 15:16:16.541 AppMessage[8304:467071] swiftStringFromClass = xxx
2015-04-28 15:16:16.541 AppMessage[8304:467071] object = <AppMessage.xxx: 0x7f98aa450490>

**Comment by evermeer** [comment]
It does however only work for top level classes, So if you have a class inside a class, then the EVReflection methods won't work. I will put this on my todo list to fix that.

**Comment by evermeer** [comment]
I have added an extra method for directly creating an object instead of first a type.
Besides that I added extra test code for the EVReflection class in the testViewController. Below you can see how it now works

```Swift
class TestObject:NSObject {
    var objectValue:String = ""
}

class TestsViewController : UIViewController {
    

    @IBAction func runTest(sender: AnyObject) {
        
        // Test the EVReflection class
        var theObject = TestObject()
        var theObjectString:String = EVReflection.swiftStringFromClass(theObject)
        NSLog("swiftStringFromClass = \(theObjectString)")
        
        if var nsobject = EVReflection.swiftClassFromString(theObjectString) {
            NSLog("object = \(nsobject)")
        }
        
        // Test the EVReflection class
        theObject.objectValue = "testing"
        var toDict = EVReflection.toDictionary(theObject)
        NSLog("toDictionary = \(toDict)")
        if var nsobject = EVReflection.fromDictionary(toDict, anyobjectTypeString: theObjectString) as? TestObject {
            NSLog("object = \(nsobject), objectValue = \(nsobject.objectValue)")
        }
```

**Comment by evermeer** [comment]
I added support for classes within classes. Swift does however generate the NSStringFromClass differently. So If you get the string it won't be the clean class name but a Swift internal class description that starts with _TtC 

When putting the TestObject within the TestsViewController class you will get this output:
```
2015-04-28 22:05:56.365 AppMessage[3662:84955] appName = AppMessage,  classStringName = _TtCC10AppMessage19TestsViewController10TestObject
2015-04-28 22:05:56.365 AppMessage[3662:84955] swiftStringFromClass = _TtCC10AppMessage19TestsViewController10TestObject
2015-04-28 22:05:56.365 AppMessage[3662:84955] object = <_TtCC10AppMessage19TestsViewController10TestObject: 0x7f86e643a770>
2015-04-28 22:05:56.366 AppMessage[3662:84955] toDictionary = [objectValue: testing]
2015-04-28 22:05:56.366 AppMessage[3662:84955] object = <_TtCC10AppMessage19TestsViewController10TestObject: 0x7f86e37ede80>, objectValue = testing
```

**Comment by InfiniteRandomVariable** [comment]
My system is XCode 6.3.1. Swift 1.2. Query will return nil if using swiftClassFromString. 

objc_getClass is a native class and solve my problems.

**Comment by InfiniteRandomVariable** [comment]
I feel working with Swift, at the moment, sometime it's better to interpolate with Objective C native method directly. The SO thread also suggests this could be one of the solutions to this issue. 

Beside, a corner case, I change some content of my data object AFTER the object is archived. It crushes in this line 
result = NSKeyedUnarchiver.unarchiveObjectWithFile(filePath)

Error: 
terminating with uncaught exception of type NSException
I opt for this solution.
http://fbernardo.org/nskeyedunarchiver-and-swift

**Comment by InfiniteRandomVariable** [comment]
I feel working with Swift, at the moment, sometime it's better to interpolate with Objective C native method directly. The SO thread also suggests this could be one of the solutions to this issue.

Beside, a corner case, I change some content of my data object AFTER the data object is being archived. It crushes in this line: 
 result = NSKeyedUnarchiver.unarchiveObjectWithFile(filePath)
Error:  terminating with uncaught exception of type NSException I 

opt for this solution.
 http://fbernardo.org/nskeyedunarchiver-and-swift
http://blog.scottlogic.com/2015/01/27/swift-exception-handling.html

**Comment by evermeer** [comment]
Thanks for the info. Strange that It does not work with you. I am using the same versions and EVReflection is used quite intensively in EVCloudKitDao which I use on a daily basis. I will try to migrate to the objc_getClass later today as you suggested. Besides that I will read through the opted solutions for your problem.

**Comment by evermeer** [comment]
I just pushed a new version to GitHub where all unarchive functions are wrapped in a try catch block. I have to do some more research for the objc_getClass function. I am getting some incompatibility issues with that.

**Comment by evermeer** [comment]
So that I will be able to give better support I created a separate repository for EVReflection. You can find it at https://github.com/evermeer/EVReflection I added a unit test project and added some unit tests. I found out that you would get nil if there is no CFBundleName. Could that also be your case? Now when there is no CFBundleName i will return the full class name. I will try to find out an alternative way to get the BundleName.

**Comment by evermeer** [comment]
There is now a better solution for getting the CFBundleName. Is this issue now solved?

**Comment by InfiniteRandomVariable** [comment]
Couldn't think of better way to solve this. Thanks!
