### ISSUE TITLE
EVCloudKitDao not connecting to app's default container if explicitly specified

### ISSUE THREAD

**Issue by tbaggett** [evermeer/EVCloudKitDao#37]
I need to connect to the same container from both my tvOS app and its TVTopShelfProvider extension. Thus far during the development of my app, I've been using its default container and EVCloudKit's publicDB and privateDB accessors. According to the [Apple iCloud documentation](https://developer.apple.com/library/prerelease/ios/documentation/DataManagement/Conceptual/CloudKitQuickStart/EnablingiCloudandConfiguringCloudKit/EnablingiCloudandConfiguringCloudKit.html) (quoted below), I should be able to connect to one app's default container from another app that is developed using the same developer team account. 

I attempted to do this by changing references to publicDB and privateDB to publicDBForContainer and privateDBForContainer and passing my app's bundle identifier name as the container name. After doing this, I don't see any error messages in the console output, but my app is no longer retrieving any data. Will I need to create a custom container to be used by the app and extension in order for this to work with EVCloudKitDao?

***Share Containers Between Apps***

*Optionally, configure your app to use multiple containers or share a container with other apps. For example, you might use one app internally to create record types and records programmatically to return a database to a known state. This app needs to share the same container as the end-user app you are developing and testing.* ***To do this, you enable the first app to use the default container of the second app*** *or create a custom container that both apps share. iOS and Mac apps can also be configured to share the same containers.*

**Comment by tbaggett** [comment]
I forgot to add that in my entitlements settings for the extension, I changed the container setting to use a custom container with the name of my app's bundle. I can provide more details if needed.

**Comment by evermeer** [comment]
You should be able to use both the .publicDB and publicDBForContainer("otherContainerID") at the same time. For instance something like this should work:
```
        let dao2 = EVCloudKitDao.publicDBForContainer("iCloud.nl.evict.myapp")
        dao2.saveItem(message, completionHandler: {record in ...
```
If you use code like that, do you see anything in the log?
Do you see a new record in that specific container?

**Comment by tbaggett** [comment]
Sorry, I should've provided more detail. I am sharing the EVCloudKitDao-dependent data access code between the app and the extension with a framework. I understand that EVCloudKitDao would allow me to use both the default and "forContainer" accessors simultaneously, but I need my shared code to explicitly specify my app's default container name so the same container will be used from both my app and extension.

I see the connections are being made to the expected container name in the console output. It just isn't returning any data when there is data in my app's default container. Should using public/privateDB and the forContainer accessors with my apps bundle ID be accessing the same container?

    12/04/2015 07:55:27:157 Marquees)[590:.] EVCloudKitDao.swift(470) initializeDatabase(_:initializationCompleteHandlers:):
	Container identifier = Optional("iCloud.com.tommyb.Marquees")
    12/04/2015 07:55:27:163 Marquees)[590:.] EVCloudKitDao.swift(464) initializeDatabase(_:initializationCompleteHandlers:):
	Account status = 1 (0=CouldNotDetermine/1=Available/2=Restricted/3=NoAccount)
    12/04/2015 08:33:47:499 Marquees)[596:.] EVCloudData.swift(573) restoreData:
	Data is restored from /var/mobile/Containers/Data/Application/98C2D061-1BA7-4D09-8254-7709731FF730/Library/Caches/Filter_allPerformances_ForUser__b1d3247b49fbcfe6b682479eb96e6f7c.bak)
    12/04/2015 08:33:48:007 Marquees)[596:.] EVCloudKitDao.swift(964) subscribe(_:predicate:filterId:configureNotificationInfo:errorHandler:):
	Subscription created for key type_Performance_id_allPerformances

**Comment by tbaggett** [comment]
I also wanted to add that I deleted the app from my Apple TV to force all the local caching to be rebuilt after making these changes.

**Comment by tbaggett** [comment]
I tried creating a new item as you suggested. I see this output in the console (twice even), with no errors otherwise. I then shut down the app and restarted it, and it still doesn't retrieve the just-created item or any of the previously-created items.

    12/04/2015 09:14:42:788 Marquees)[596:.] EVCloudData.swift(743) upsertObject(_:item:):
	upsert 84D06CC9-4E0D-4D1E-841B-BE0E100AAEB6 Performance

**Comment by evermeer** [comment]
I will do some double container tests tomorrow...

**Comment by tbaggett** [comment]
Thank you for looking into it. One more piece of info, I see the test item that I just created in my app's default container when inspecting it with the iCloud dashboard. So it seems to be working when sending data to iCloud, it just isn't retrieving it for some reason. Keep in mind also that in my case, I am pointing EVCloudKitDao to my framework's bundle using this call:

    EVReflection.setBundleIdentifier(Performance)

**Comment by tbaggett** [comment]
This is also using the version of your library with my modifications. I hope I haven't broken anything...

**Comment by tbaggett** [comment]
More info on this. After stepping away for a bit, I realized the code that creates the new Performance instance was still making the call directly to the default container using the privateDB accessor. I changed this to using privateDBForContainer and found that the data was retrieved when I restarted the app, however it was created in the public default zone instead of the private default zone. 

I suspect my changes may be at fault here, so I will investigate it further and commit fixes if that is the case. I will let you know my findings either way.

**Comment by evermeer** [comment]
Great to hear that you found the cause.

**Comment by tbaggett** [comment]
I have fixed the issue in my fork. See https://github.com/tbaggett/EVCloudKitDao/commit/d30ca93dc1287f6d1c77b2d73aa4ca50ee7caaa3. 

I believe this bug exists in your unmodified version as well. The EVCloudKitDao privateDBForContainer method calls the EVCloudKitDao constructor without changing the initial IsPublic value of the isType property to IsPrivate. So it is connecting to the public db instead of the private one, then assigning it to the containerWrapperInstance.privateContainers dictionary.

**Comment by evermeer** [comment]
I have added code to set the private container type to isPrivate. This should now be fixed

**Comment by tbaggett** [comment]
Yes, this is working fine now.
