### ISSUE TITLE
Unknown Errors

### ISSUE THREAD

**Issue by traw1234** [evermeer/EVCloudKitDao#4]
When I try to run it I get these three errors: 

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by evermeer** [comment]
Do you have cocoapods version 0.36 or later? And did you run  'pod install' from the EVCloudKitDao folder?

**Comment by evermeer** [comment]
Is this still an issue or can I close this?

**Comment by traw1234** [comment]
It is all fixed now, thanks
