### ISSUE TITLE
Can a single record type be defined by multiple child classes?

### ISSUE THREAD

**Issue by tbaggett** [evermeer/EVCloudKitDao#40]
I was hoping to create a single private CKRecord type that contains fields that are defined by multiple child classes. For example, an ApplicationOptions record type that contains all options, but having those options divided up into child classes, like the example below. I thought a way to do this might be to have the child classes inherit from EVObject, like so:

    public class ApplicationOptions: EVCloudKitDataObject {
        public var audio = AudioOptions()
        public var video = VideoOptions()
        public var playback = PlaybackOptions()
    }

    public class AudioOptions: EVObject {
        public audioPreferenceOne: Bool = false
    }

    public class VideoOptions: EVObject {
        public videoPreferenceOne: Bool = false
    }

    public class PlaybackOptions: EVObject {
        public playbackPreferenceOne: Bool = false
    }

The desired result would be an ApplicationOptions CKRecord that contains fields named something like audio_audioPreferenceOne, video_videoPreferenceOne and playback_playbackPreferenceOne. In this case, there will only ever be a single record instance for application options, and it would be overkill imho to also create separate record types for each of the child classes. They are also expected to only result in a single record instance per user.

When I attempt something like the above example, I get this unhandled exception:

    *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Objects of class __NSDictionaryM cannot be set on CKRecord'

Is there any way to accomplish this type of thing, or is this beyond the scope of what is supposed to be possible? Thanks...

**Comment by tbaggett** [comment]
I also tried using a struct instead of a class for the child classes. It didn't work either, but due to an assertionFailure:

    fatal error: ERROR: valueForAny unkown type ChildStruct(preference: true), type ChildStruct. Could not happen unless there will be a new type in Swift.

**Comment by evermeer** [comment]
I think that could be accomplished by changing the toCKRecord and fromCKRecord functions of EVCloudKitDao. The toCKRecord would be easy. The for loop should be moved to a separate function where you could check the value for type NSDictionary and then call itself recursively. The fromCKRecord would be a little more difficult. The CKRecordToDictionary should be called in a separate step where should be detected if a dictionary item should actually be in a separate dictionary. This should also be done recursively.

I do think it's a good idea to implement this. I will put this on my todo list.

**Comment by tbaggett** [comment]
Okay, thanks. In the meantime, I can create separate classes for the data objects being used in my app and the EVCloudKitDataObject-derived ones and map them.

Any thoughts on a timeline to see this done? I have no idea how long your todo list is. :-)

**Comment by evermeer** [comment]
Well... priorities can change :)  This issue is relatively easy to fix, so I will move it up on the list. I will have a look at it later today.

You should be aware of one thing when using this. Since EVCloudData is using the same predicate for CloudKit and comparing the notification objects to see for what connection these are, you could not use EVCloudData with a predicate for properties in child classes.

**Comment by evermeer** [comment]
Almost ready with this one... Will probably push this later this evening... Im now testing this

**Comment by tbaggett** [comment]
Sweet! I won't get to try it out for a couple of days, but will look for it and give it a try when I get back to things.

**Comment by evermeer** [comment]
Okay, I just pushed version 2.15.0 to GitHub with this change. Since CloudKit does not accept special characters for field names, I used a double underscore. Because of this you now have the following limitations for your field names:
- You can not use double underscores inside your own field names.
- You cannot end a sub object field name with a single underscore.

I added a test case to the TestViewController.swift. As you can see there I create an Invoice that has 3 Address sub objects.

Please let me know if this works for you

**Comment by tbaggett** [comment]
I've updated and merged the latest with my fork and it all looks good. I'm hoping to work on applying it to my use cases today. I will let you know how it goes. Thanks for adding support for this!

**Comment by tbaggett** [comment]
Are your changes expected to support optional sub objects if they aren't initialized? I found that this code works when createRecordTypes is called:

    public class EVCloudKitDaoTest: EVCloudKitDataObject {
        public var testProp = "This is a string test property"
        public var sub = SubProp()
    }

    public class SubProp: EVCloudKitDataObject {
        public var subPropTest = "This is another string test property"
        public var subsub = SubSubProp()
    }

    public class SubSubProp: EVCloudKitDataObject {
        public var yaSubPropTest = "Yet another string test property"
    }

The above code results in the following fields being created in the CK record:

    EVCloudKitDaoTest
        sub__subPropTest: String
        sub__subsub__yaSubPropTest: String
        testProp: String

If I change the "sub" var to an optional and don't assign anything to it like this, the only field that is created is the "testProp" String property.

    public class EVCloudKitDaoTest: EVCloudKitDataObject {
        public var testProp = "This is a string test property"
        public var sub: SubProp?
    }

    public class SubProp: EVCloudKitDataObject {
        public var subPropTest = "This is another string test property"
        public var subsub = SubSubProp()
    }

    public class SubSubProp: EVCloudKitDataObject {
        public var yaSubPropTest = "Yet another string test property"
    }

If I then change the optional to have an instance assigned, createRecordTypes() works as expected. Its okay if I need to fully populate the instances passed to the createRecordTypes method. However, I missed that requirement if it is documented or shown in the examples.

        // Works as expected
        public var sub: SubProp? = SubProp()

**Comment by evermeer** [comment]
It's true, when initially creating a record type, then nil values will be the same as not sending the key value pair for that property to CloudKit. When you use the code for creating a recordType, then that field won't be created. It's also something that you need to be aware of when updating a record. You won't be able to set an existing value to nil. You can only clear a value. CloudKit does not have support for true nil values. Or at least that was the case more than a half year ago when I was playing around with nil values.

**Comment by tbaggett** [comment]
Thanks for the info. That is unfortunate. I will have to rethink how I have implemented some of my data classes. This is still the case, based on the CloudKit documentation, which was updated as recently as 12/17/2015:

**Handle missing keys gracefully in your code.** For each record you create, you are not required to provide values for all keys contained in the record type. For any keys you do not specify, CloudKit sets the corresponding value to nil. Your app should be able to handle keys with nil values in an appropriate way. Being able to handle these “missing keys” becomes important when new versions of your app access records created by an older version.

I also verified the behavior with my own simple test:

        let recId = CKRecordID(recordName: "115")
        let rec = CKRecord(recordType: "TBTest", recordID: recId)
        rec["testPropOne"] = "This is a test"
        rec["testPropOne__subProp"] = nil
        
        let container = CKContainer.defaultContainer()
        let db = container.publicCloudDatabase
        db.saveRecord(rec) { record, error in
            if let _ = error {
                NSLog("ERROR!")
            }
            if let _ = record {
                NSLog("SUCCESS!")
            }
        }

After executing the above code, I now have a new "TBTest" record type, but it doesn't contain a "testPropOne__subProp" property. I'm closing the issue.

**Comment by tbaggett** [comment]
Whoops, I was thinking I had created a separate issue for the nil values when I closed this issue. I'm reopening this one until I finish testing. Also, in regards to what you were saying about updating an existing record, what do you mean by "clearing a value" as opposed to setting it to nil?

**Comment by evermeer** [comment]
It will only update the fields where you supply a value. Since you cant save a nil value, you also will not be able to change an existing value to nil. You have to send something like an empty string.

**Comment by tbaggett** [comment]
Got it. Okay, I will look at refactoring my data classes as needed to account for this, then test your changes with mine afterwards. Thanks for the clarifications/explanations.

**Comment by tbaggett** [comment]
I'm making progress, but have run into another unexpected behavior. I have some private vars declared in some of my data classes:

    private var isPerUser: Bool
    private var containerName: String
    private var referencedInst: ObservableCloudData<T>?

I expected that private vars would be ignored, but they are mapped to the CK record structure. After looking through your EVReflection documentation, I tried adding this:

    override public func propertyMapping() -> [(String?, String?)] {
        return [("containerName", nil), ("isPerUser", nil), ("referencedInst", nil)]
    }

Adding this also had no effect; the properties are still added. Is there a way to tell EVCloudKitDao to ignore a property?

**Comment by evermeer** [comment]
Ah, that should have worked. I just found out that the propertyMapping only works when doing a key cleanup. For EVCloudKitDao I did not use that. I think that when you added a propertyMapping it should always dot that. The key cleanup should only do the pascal case, camel case and snake case conversions. I'm now moving the code out of the key cleanup into the main property processing...

**Comment by evermeer** [comment]
I just published EVReflection 2.15.0
Your code above with the propertyMapping should now work. 
I tested it with the following code:
```
    func ingnoreFieldTest() {
        let myObj = testObject()
        myObj.saveString = "save this"
        myObj.ignoreString = "Forget about this"
        
        let record = EVCloudKitDao().toCKRecord(myObj)
        EVLog("record from object: \(record)")
    }
}

public class testObject: EVCloudKitDataObject {
    private var ignoreString: String = ""
    var saveString: String = ""

    override public func propertyMapping() -> [(String?, String?)] {
        return [("ignoreString", nil)]
    }
}
```
The output is then:
```
12/28/2015 11:27:33:461 AppMessage)[39655:.] TestsViewController.swift(313) ingnoreFieldTest():
	record from object: <CKRecord: 0x7ff31b77b7f0; recordType=testObject, recordID=174A4653-8772-4BF5-AF25-128FFAB8549F:(_defaultZone:__defaultOwner__), values={
    saveString = "save this";
}>
```
As you can see only the saveString is in the CKRecord

**Comment by tbaggett** [comment]
Awesome, thanks for taking care of that. I will update and give it a try, then continue getting all my data classes working. I will let you know how it goes.

**Comment by tbaggett** [comment]
Sorry but I just thought of another question. Given that EVCloudKitDao recognizes private variables and maps them by default, does it not have a problem restoring their values when reading from iCloud? I would think that it wouldn't be able to assign values to the private properties. If it does work, that opens up more possibilities.

**Comment by evermeer** [comment]
values are set using the 'setValue forKey' which does not take into account if a variable is private or not. Which is fortunate because Mirror will also not report if a variable is private or not. This way I don't have to worry about it at all.

**Comment by tbaggett** [comment]
Perfect, thanks for the confirmation.

**Comment by evermeer** [comment]
👍🏼🎄🎁🍾

**Comment by tbaggett** [comment]
FYI, it looks like you didn't commit the 2.15 changes to the repo. I just pulled and see the last commit being 3 days ago, https://github.com/evermeer/EVCloudKitDao/commit/3535008694332b241111f3fc3289e82878c9dbcf. Can you commit the changes so I can merge them to my fork? Thanks!

**Comment by tbaggett** [comment]
Doh, never mind, I'm looking at EVCloudKitDao, not EVReflection. My bad! :-)

**Comment by tbaggett** [comment]
Everything looks good on this issue at this point to me. Be aware that I've only been writing to CK thus far, not reading stuff back. Its okay with me if you want to close this issue. I can reopen it if I discover any issues later. Thanks again for knocking this out!

**Comment by tbaggett** [comment]
I'm continuing to test and have run across an issue. When data is restored from the local cache, I see multiple warnings like this:

    WARNING: The class 'AudioOptions' is not key value coding-compliant for the key 'muteNarration'
    There is no support for optional type, array of optionals or enum properties.
    As a workaround you can implement the function 'setValue forUndefinedKey' for this. See the unit tests for more information

In some of the cases, these are indeed enums or optionals. However, the enums are based on Ints and are using EVRawInt. Also, in one case, the property is a string. 

All the properties that are generating this warning are set to private scope. I found that the warning is no longer issued for the string property if I change its scope to public. Any thoughts on this?

**Comment by evermeer** [comment]
For enum values you need to set EVRawInt (or any of the other EVRaw*)  so that the raw value can be retrieved from the enum when going to the properties using the Mirror function. Besides that, you also need to implement the 'setValue forUndefinedKey' function in order to be able to set the value. A complete sample can be found at: https://github.com/evermeer/EVReflection/blob/9a9e6f4c95378b71b24363a25241a21e213acbcd/EVReflection/EVReflectionTests/EVReflectionWorkaroundsTests.swift#L65-65

I was under the impression that the setValue forKey function also worked on private properties. I will do some tests now.

**Comment by evermeer** [comment]
It looks like Mirror will return private properties without any indication of what its accessory type is (private, internal, public) but the 'setValue forKey' will use this and in our case properties can not be private. It looks like there is no other option available

**Comment by tbaggett** [comment]
Okay, I understand on the EVRawInt and setValue forUndefinedKey points now. I was using EVRawInt, but I thought that it took care of everything, not just reading. I had also started implementing setValue forUndefinedKey for properties, but stopped when I saw it complaining about the string property. I knew something wasn't right at that point.

"setValue forKey" not ignoring scope is really unfortunate. I refactored several data classes to use that trick . I have overridable default options in my app, where defaults can be set application wide, per document or per element. I was expecting the private properties to be used to store each level's setting, but not expose those properties outside the class. Instead, calculated properties that take the inheritance into account would be exposed. I will have to rethink how I'm doing that now.

Oh well, live and learn, right? :-) Thanks for investigating those issues.

**Comment by tbaggett** [comment]
Happy 2016! Unfortunately I think I'm starting the new year off with another bug. I have an issue with one of my data classes. It is getting trashed, possibly by the local cached data restore process. Here are the details, please let me know what you think.

I have an EVCloudKitDataObject-derived class that contains another EVCloudKitDataObject-derived class as an instance property. That class in turn contains an Event instance property. The Event class isn't a data class, so I am specifying that it should be ignored by EVReflection.

	// This class contains an instance of the PerformanceOptions class, which derives from CloudOptions, both defined below.
	public class PerformanceContent: EVCloudKitDataObject, DidChangeEventSourceProtocol {
		public let didChange = Event()

		...
	
		// Configuration options for this performance
		public var options = PerformanceOptions() {
			willSet {
				options.didChange.detachCascadingEvent(didChange)
			}
			didSet {
				options.didChange.attachCascadingEvent(didChange)
			}
		}

		...
	
		override public func propertyMapping() -> [(String?, String?)] {
			return [("didChange", nil)]
		}
	}

	public class PerformanceOptions: CloudOptions {
		public required init() {
			super.init(parentOptions: MarqueesAppModel.instance.appOptions.getItem(), scopeId: .Performance)
		}
	
		public required init(parentOptions: CloudOptions?, scopeId: OptionScopes) {
			super.init(parentOptions: parentOptions, scopeId: scopeId)
		}
	}

	public class CloudOptions: EVCloudKitDataObject, DidChangeEventSourceProtocol {
		public let didChange: Event
	
		public required init() {
			fatalError("Must call the parentOptions/scopeId initializer")
		}
	
		public required init(parentOptions: CloudOptions?, scopeId: OptionScopes) {
			// NOTE: Tried initializing this like this and doing immediate assignment in the declaration, as seen above in the PerformanceContent class. Same result seen either way.
			didChange = Event()
		
			playback = PlaybackOptions(parentOptions: parentOptions?.playback, scopeId: scopeId)
			playback.didChange.attachCascadingEvent(didChange)
		
			audio = AudioOptions(parentOptions: parentOptions?.audio, scopeId: scopeId)
			audio.didChange.attachCascadingEvent(didChange)
		
			video = VideoOptions(parentOptions: parentOptions?.video, scopeId: scopeId)
			video.didChange.attachCascadingEvent(didChange)

			super.init()
		}

		public var playback: PlaybackOptions
		public var audio: AudioOptions
		public var video: VideoOptions
	
		override public func propertyMapping() -> [(String?, String?)] {
			return [("didChange", nil)]
		}
	}

If I delete the app then reinstall and launch it without locally-cached data being available, the didChange property references an Event instance as expected. However, if I close the app and relaunch it, now with locally-cached data available, the didChange property is now referencing an NSTaggedPointerString instance that is set to "recordID" instead of the expected Event instance. 

Does this sound like something in your framework could be overwriting this property value? Thanks as always.

**Comment by evermeer** [comment]
Saving and loading objects is done through the NSCoding protocol. When saving an object, it will encode all properties returned by the .toDictionary. Since this is a standard EVReflection function, it should indeed exclude whatever you defined in your propertyMapping. Decoding will work almost the same. It will read all properties from the coder based on the properties that are returned by .toDictionary. Again the didChange should be ignored.

Your code is using an init to set the didChange property. When loading an object using NSCoding it will instantiate the object using the init(withCoder:) initializer. because of that your init won't be called and the didChange property won't be initialized. The value that you found was probably a random pointer issue. Can't you just initialize it using:
 public let didChange: Event = Event()

**Comment by tbaggett** [comment]
Thanks for the feedback, especially on the holiday! I had tried the direct initialization as you suggested and found the same result. I mentioned that in a comment in the provided code:

    // NOTE: Tried initializing this like this and doing immediate assignment in the declaration, as seen above in the PerformanceContent class. Same result seen either way.
    didChange = Event()

I will investigate further and see if I can determine the problem source.

**Comment by evermeer** [comment]
I thought about one other thing... I don't think its an issue in your case but you never know.
You might try to move the super.init() to the first line of your init. I thought I have read somewhere that you should do that before accessing local properties.

**Comment by tbaggett** [comment]
Thanks for the suggestion, but Swift/Xcode complains when I do that. It shows an error that reads "Property 'self.playback' not initialized at super.init call" when I move the super.init() call to the top of the function.

I suspect it is something that I'm not handling on my end correctly. I just wanted to run it by you in case it could be something with your recent changes before. I will have to thoroughly review my code top to bottom to see if I can determine what is happening.

**Comment by tbaggett** [comment]
One thing you may be able to help with, given my still-newb exposure to all things iOS development... 

I'm stepping through code and inspecting variables and properties in Xcode. Most of the time, this works great. However, sometimes when doing this, it doesn't show any of the values. You can take a look at [this screen shot](https://www.dropbox.com/s/1hzbnjugqlc32pv/XcodeDebugNoInspectorValues.png?dl=0) to see what I'm talking about.

Any idea what to do to inspect parameters, properties, etc., in these cases? Thanks!

**Comment by evermeer** [comment]
I often use the output window and use one of these commands:
po myVar
P myVar
po "/(myVar)"

**Comment by tbaggett** [comment]
Thanks for those tips. I will give them a try the next time I run into that Xcode issue. I took the weekend off, so this is my first chance to investigate my data problem further. I think I see examples in my code where the init(withCoder:) initializer being called instead of my other initializers introduces problems.

Please take a look at the provided example code. In your experience, would the object instance referenced by both ParentContainer::options and ChildContainer::options::parentOptions point to the same Options class instance after being restored from disk via NSCoder? Or would they be two distinct instances?

Also, if both references would point to the same instance, does your current code allow different properties to be stored/retrieved locally than those being stored in CloudKit? It isn't a big deal if not, and I would be surprised if that is the case. I will just need to store some properties in CloudKit that I didn't think would be necessary.

    public class Options: EVCloudKitDataObject {
        public let parentOptions: Options?
        
        public convenience init(parentOptions: Options? = nil) {
            self.init()
            self.parentOptions = parentOptions
        }
    }

    public class ParentContainer: EVCloudKitDataObject {
        public let options: Options
        
        public let child: ChildContainer
        
        public required init() {
            // Instantiate an instance of the Options class here, then pass it as the parent to our child container
            options = Options()
            
            child = ChildContainer(parentOptions: options)
        }
    }

    public class ChildContainer: EVCloudKitDataObject {
        public let childOptions: Options
        
        // When the ParentContainer and ChildContainer are restored via NSCoding, will the ParentContainer's options property and the ChildContainer's options property's parentOptions property both point to the same instance?
        public convenience init(parentOptions: Options) {
            childOptions = Options(parentOptions: parentOptions)
        }
    }

Thanks as always.

**Comment by evermeer** [comment]
Ah, that's a good one. I think I have to create a test to see if you have the same instance or 2. I'm using generic NSCoding methods, so i guess it would be the same as any other code that is using NSCoding. Creating a unit test to test this would not be so hard to do. Let me see if I can squeeze that in today 😀

What is processed by NSCoding is the same as what's processed using the .toDictionary. So the propertyMapping will also be applied. Now I think of it, it might be a good idea to change the performKeyCleanup for that function to support more situations like:
- raw - where everything comes pure from the Reflect
- standard - where the propertyMapping and propertyConverter are executed
- cleaned - where keywords, illegal characters, pascal, camel and snake case conversions are executed.

Then NSCoding should use the raw version since you want identical objects back.
What do you think of this approach?

**Comment by evermeer** [comment]
It appears to be working. See the unit test: https://github.com/evermeer/EVReflection/blob/440db32c42810605a5d697879b315aa95a2ae8ca/EVReflection/EVReflectionTests/EVReflectionEVObjectTests.swift#L116-116

**Comment by tbaggett** [comment]
Thanks for looking into it, especially for taking the time to test it. I didn't mean to put you to work there! I thought you might know from past experience.

I think the "raw", "standard" and "cleaned" options would be great. I didn't ask for such a thing because I thought my approaches might've been an edge case situation.

**Comment by tbaggett** [comment]
FYI, locally-cached data is still loaded if you change the caching strategy to None after caching was previously enabled. I wouldn't think this would matter unless there are explicit use cases where the caching strategy would be intentionally changed from/to None based on certain criteria. 

Currently the code doesn't consider the caching strategy when attempting to restore data. I just deleted my app to remove the cache files in my case, since disabling caching is a temporary fix for the issue I ran into.

**Comment by evermeer** [comment]
Don't worry... I was curious about the issue myself. 
I will create a new issue for the raw, standard and cleaned issue since it's not really related to this issue.

I will also create a new issue for your caching issue. It might not be a problem for you, but it is a bug.

**Comment by evermeer** [comment]
I think all outstanding issues mentioned here are now new issues. If there is still something wrong with child objects, then please create a new issue for that.
