### ISSUE TITLE
Caching Data

### ISSUE THREAD

**Issue by ahanmal** [evermeer/EVCloudKitDao#41]
Hey there!

I'm using EVCloudKitDao's query method (I'm accessing mostly static data) and was wondering how the caching mechanism worked? Do I need to call `.connect` to enable the caching mechanism? Any time I close the app and reopen the app, the query's are run. Does the cache support what happens via a query and is it persisted between sessions?

Thanks!

**Comment by evermeer** [comment]
It's build in into the connect in EVCloudData only. For a regular query it's easy to do that yourself. All classes are NSCoding compatible. You only have to save and restore it. You could use the code that is available in the EVCloudData class:

```
class MyCode {
    var dao = EVCloudKitDao.publicDB
    var data = EVCloudData.publicDB
    var result: [MyObject]?

    func myQuery() {
         self.result = data.restoreData("MyObject_Query1.dat") as? [MyObject]
         // now something like tableView.reloadData?
        dao.query(MyObject(), completionHandler: { results, isFinished in
           data.backupData(results, toFile: "MyObject_Query1.dat")  
           self.result = results
           // now again something like tableView.reloadData?
       }, errorHandler: { error in
       })
    }

}
```

**Comment by ahanmal** [comment]
Ahh. That makes sense. Implementing it myself should be pretty straightforward.

Thanks!

**Comment by ahanmal** [comment]
So - I tried doing this but it seems that when the data gets serialized into an NSDictionary and then saved. However, when I retrieve the object, it does not deserialize the data into the original objects, they remain as dictionaries. Any way to deserialize this back?

**Comment by evermeer** [comment]
I'm not sure where that dictionary comes from in your case. The results parameter is an array of objects. When you save it, then it should be the same when you load it. Saving and loading an object structure should be quite strait forward. No intermediate conversion is necessary. Maybe you could show a code snippet of your problem? 

Underneath it is using the NSCoding functionality that is in EVReflection. Here is a simple test that shows the most basic functionality:
https://github.com/evermeer/EVReflection/blob/5b09a17b61459b37281f3de26442ebb56b5f177e/EVReflection/EVReflectionTests/EVReflectionEVObjectTests.swift#L93-93

**Comment by evermeer** [comment]
Sorry, I almost missed this email. Maybe next time could you create an
issue in GitHub? Then as long as it's open I could not overlook it.

Saving and reading is handled in the EVReflection module. It should be
quite strait forward. You should be able to save an object or an array of
objects and then just load it again.

Here is a simple unit tests that shows the basic functionality:
https://github.com/evermeer/EVReflection/blob/5b09a17b61459b37281f3de26442ebb56b5f177e/EVReflection/EVReflectionTests/EVReflectionEVObjectTests.swift#L93-93


2015-12-27 1:26 GMT+01:00 Ahan Malhotra <notifications@github.com>:
