### ISSUE TITLE
Pending notifications not checked in all cases

### ISSUE THREAD

**Issue by appsird** [evermeer/EVCloudKitDao#42]
Pending notifications should be checked 1) when your App launches, or 2) becomes active, or 3) it receives a push notification, it should first check with CloudKit if there are CKNotification objects pending to be processed". 

Thus, there should be checks for notifications in methods:

didFinishLaunchingWithOptions
applicationDidBecomeActive
didReceiveRemoteNotification

The example covers (1) and (3), though does not check notifications for (2). This could have adverse affect if the app is backgrounded, then foregrounded, notifications might be missed/not processed.

Brian

**Comment by evermeer** [comment]
true...
I will update the demo.
Thanks for reporting this.

**Comment by evermeer** [comment]
demo is updated.
