### ISSUE TITLE
Support for silent notifications

### ISSUE THREAD

**Issue by appsird** [evermeer/EVCloudKitDao#43]
EVCloudKitDao does not currently appear to support silent notifications. For example, when silent notifications are received, the method didReceiveRemoteNotification:fetchCompletionHandler  will be called in place of the current AppDelegate didReceiveRemoteNotification.

Certain fields should not appear in the notification info which trigger CloudKit into recognizing this is a silent notification.

**Comment by evermeer** [comment]
You should be able to implement that by just using this:
```
    func application(application: UIApplication, didReceiveRemoteNotification userInfo: [NSObject : AnyObject], fetchCompletionHandler completionHandler: (UIBackgroundFetchResult) -> Void) {
        EVLog("Push received")
        EVCloudData.publicDB.didReceiveRemoteNotification(userInfo, executeIfNonQuery: {
            EVLog("Not a CloudKit Query notification.")
            }, completed: {
                EVLog("All notifications are processed")
                completionHandler(.NewData)
        })
    }
```

Are you saying that this does not work correctly? Or do you need additional logic?

**Comment by appsird** [comment]
Once the above code is included in the AppDelegate, the forerunner didReceiveRemoteNotification method will not longer be called, whether the notification is received in foreground or backgound. 

Also, to specify a silent notification the shouldSendContentAvailable  needs to be set true.

let notificationInfo = CKNotificationInfo()
notificationInfo.shouldSendContentAvailable = true
subscription.notificationInfo = notificationInfo

In addition, the background remote notification capability needs to be set.

Possibly you can include in your docs how to enable background silent notifications, as it requires multiple parts to be implemented. This is not really a bug, but a 'feature request' to allow other users to know what to do to implement silent notifications.

**Comment by evermeer** [comment]
shouldSendContentAvailable is already the default
I added comments above the methods in the app delegate.
