### ISSUE TITLE
2.16.0 fails to build due to TestViewController's ignoreFieldTest code

### ISSUE THREAD

**Issue by tbaggett** [evermeer/EVCloudKitDao#46]
FYI, I just updated my branch to incorporate your latest changes. I am seeing a build failure due to this line of code in TestsViewController::ignoreFieldTest():

    let record = EVCloudKitDao().toCKRecord(myObj)

The reported error is: 

    'EVCloudKitDao' cannot be constructed because it has no accessible initializers

**Comment by evermeer** [comment]
I have corrected this and pushed it to GitHub
