### ISSUE TITLE
2.16.0 tvOS Issue: UIBackgroundFetchResult prohibited in tvOS

### ISSUE THREAD

**Issue by tbaggett** [evermeer/EVCloudKitDao#47]
The UIBackgroundFetchResult enum is prohibited from use in tvOS. Sample app's AppDelegate didReceiveRemoteNotification example should be documented accordingly for tvOS developers who are using the iOS sample app as a guide.

Enumeration declaration from tvOS 9.1's UIApplication.h file:

	typedef NS_ENUM(NSUInteger, UIBackgroundFetchResult) {
		UIBackgroundFetchResultNewData,
		UIBackgroundFetchResultNoData,
		UIBackgroundFetchResultFailed
	} NS_ENUM_AVAILABLE_IOS(7_0) __TVOS_PROHIBITED;

**Comment by evermeer** [comment]
In the AppDelegate i put now have put this in a conditional compilation block with an comment. Should be clear enough now.
