### ISSUE TITLE
deprecation warnings when compiling for iOS 9.2

### ISSUE THREAD

**Issue by appsird** [evermeer/EVCloudKitDao#48]
fyi: I receive the following deprecation warnings in some/all view controllers when compiling in iOS 9

.../RootViewController.swift:100:75: 'firstName' was deprecated in iOS 9.0: Use -[[CKDiscoveredUserInfo displayContact] givenName]

What is the plan (if any) to migrate the project forward to ios9?

**Comment by evermeer** [comment]
I have pushed a new version to GitHub where the method for getting the name is now conditional based on the iOS version.

deprecated does not mean that it does not work. It only means that the function will probably be removed and will become unsupported in a later version. I want to keep the project iOS version 8 compatible. The Base SDK is 8.0 which means that it should work on version 8.0 and any version after that. I don't think there is anything to migrate to iOS 9. It already works on every iOS from 8.0.

**Comment by appsird** [comment]
Oddly, this check works in AppMessage project though generates a warning in my own:

Unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true <https://www.google.com/search?client=safari&rls=en&q=Unnecessary+check+for+'iOS';+minimum+deployment+target+ensures+guard+will+always+be+true&ie=UTF-8&oe=UTF-8>

Tried downloading new CocoaPods as one board suggested:

 gem install cocoapods -v 1.0.0.beta.2

Though, no positive effect. Warning still appears.

Also discussed here:

http://stackoverflow.com/questions/32534345/warning-unnecessary-check-for-minimum-deployment-target

For now, I’ll remove the check and use the line/version for iOS 9.0

**Comment by evermeer** [comment]
you probably are using a deployment target of 9.0. The target of AppMessage is 8.0. Updating cocoapods would not help because it's only in the AppDemo and not in the library. If you do want to keep the target at 9.0 then you can indeed just skip the check and use the 9.0 syntax.
