### ISSUE TITLE
Look Me Up By Email feature

### ISSUE THREAD

**Issue by appsird** [evermeer/EVCloudKitDao#49]
In iOS Settings->iCloud->iCloud Drive a setting exists:

"Look Me Up By Email"

Clicking it shows description:

"Apps that have requested permissions to look you up by your Apple ID will appear here People who look you up will see your first and last name".

AppMessage is not listed, nor any other app. How does this feature relate to EVCloudKitDao if at all? When will an app be listed, i.e. what API call would generate an entry here. Documentation on search seems fairly light. When the iCloud Drive switch is turned off, the "Look Me Up By Email" setting persists seeming to indicate iCloud Drive is not a requirement for it's intended capability.

Is this feature related to the call EVCloudKitDao.publicDB.discoverUserInfo?

Also, listed below the "Look Me Up By Email" setting is a list of Apps, including AppMessage. Please confirm this is a selective enable/disable of iCloud Drive itself on a per app basis. Can't seem to locate any documentation describing this feature.

**Comment by evermeer** [comment]
The EVCloudKitDao function discoverUserInfo will execute a discoverUserInfoWithUserRecordID on the CloudKit container. The documentation for that function states:

> Use this method to retrieve information about a user for which you already have a user record ID. The > user you are searching for must meet the following criteria:
> - The user must have run the app.
> - The user must have granted the CKApplicationPermissionUserDiscoverability permission for this container.

An other EVCloudKitDao function that requires similar is allContactsUserInfo

That lookup is indeed on per app basis. If you have enabled it for AppMessage, then you can only be found from within an other AppMessage app by an account that has your details in it's contacts list.
