### ISSUE TITLE
Can I assign sort descriptors when using EVCloudData to control result sorting?

### ISSUE THREAD

**Issue by tbaggett** [evermeer/EVCloudKitDao#51]
Title says it all. I'd like to specify sorting criteria when calling EVCloudData.connect(...), which will need to in turn pass the criteria to EVCloudKitDao. I don't currently see a way to do that. Am I missing it, or is it something you plan to add? Thanks.

**Comment by evermeer** [comment]
This is an other todo. I don't think it will be a lot of work. The only thing needed is to extend the query and connect methods to accept a sort descriptor and set it on the CKQuery.

For easy creating a sort descriptor I could create a helper function that accept a filename and an order.
Or is that such a default sort descriptor that it would be good enough to pass the sort field plus order to the query and connect methods?

... i did some reading into sort descriptors. I think it would be good enough to pass on a fieldName plus order to the query and connect functions. agree?

**Comment by tbaggett** [comment]
Specifying a single field name and order in the query and connect functions is sufficient for what I'm doing at the moment. However, it won't be for anyone needing multi-field sort, which is supported by CloudKit. 

A separate helper function that accepts an array of NSSortDescriptor instances could take care of that. Just my two cents of course! :smile:

**Comment by evermeer** [comment]
I now have created an extra parameter orderBy where you can put something in like:
Ascending("category").Descending("creationDate")
Which will first sort on category and then on the creationDate in descending order.

It will take some more time to let this work correctly with the .connect function. Currently new records that drive through push notifications are added to the top of the array. That is OK when the default sort is creationDate. When the sort is different, an new record should probably be inserted somewhere in the middle of the array. Tomorrow I will try to implement that.

**Comment by tbaggett** [comment]
That sounds good. Thanks for adding support for it. I will look for a new version once you have everything taken care of.

**Comment by evermeer** [comment]
I pushed the solution to GitHub. Could you please test the trunk version before I create a new cocoapod version for this? You can see the demo in the LeftMenuViewController. You can test it by changing the Ascending in Descending and visa versa. The code there now looks like this:
```
        EVCloudData.publicDB.connect(
            News()
            , predicate: NSPredicate(value: true)
            , orderBy: Ascending(field: "Subject").Descending("creationDate")
            , filterId: "News_All"
            , ......
```

**Comment by tbaggett** [comment]
Okay, sure, I will grab it and test it later today and get back to you.

**Comment by tbaggett** [comment]
Okay, I'm a "day late and a dollar short" as they say around these parts, but I managed to test this today. It seems to be working as desired, but I only tried a specifying a single Ascending order using one of my class's custom field names. It looks good to me!
