### ISSUE TITLE
Results aren't sorted as specified when new items are created and saved

### ISSUE THREAD

**Issue by tbaggett** [evermeer/EVCloudKitDao#55]
When using the recently-added sorting capability in EVCloudData, new items that are created and saved aren't added to existing filter results in the order specified by the filter's sorting criteria. The lists are sorted correctly if I restart the app with local caching disabled, in which case the results are retrieved from CloudKit again. Caching may not effect this, but I currently have it disabled and these are the results I see in that case.

**Comment by evermeer** [comment]
All data insertions and update go through the upsertObject function. At the end of that function there is a sort command that will make sure the collection is in the right order. This was after the callback functions were called. This was wrong. I moved it up right after the data collection was mutated. This will ensure that the data will be sorted when the callbacks are made. This has now been pushed as version 2.19.0
