### ISSUE TITLE
Subscribe to new Message \ News doesn't work

### ISSUE THREAD

**Issue by GuyKahlon** [evermeer/EVCloudKitDao#56]
Hi, 

Subscribe for new Message \ News doesn't work for me, Any idea?

**Comment by evermeer** [comment]
First we should check if we can make the subscription for the news work. If you start up the app, do you see any warnings in the output window? If not, then go to the CloudKit dashboard, go to the News recordType and add a new news item. Do you see that coming in in the app? (wishing a couple of seconds). If not, then close the app and start it again. Do you now see the news item that you added in the dashboard?

**Comment by GuyKahlon** [comment]
Hey, 
Thanks for your quick response.

If I start up the app, I don't see any warnings in the output window

If I add a new news item for the CloudKit dashboard I don't get a notification with the new item, but if I close the app and start it again I see the new news items.
Same behavior with the chat messages, If I send a new message for the user to the other users I see the message just after closing and starting the app.

So, if I understand correctly, everything works fine apart from the Notifications.
I check also the Subscription Types on the CloudKit dashboard and I see 3 types:
Message:To_ID
Message:From_ID, To_ID
News

Thanks again

**Comment by evermeer** [comment]
The only thing I can think of is that you declined for notifications the first time the app was started. Could you try checking the notification settings in the settings app?

**Comment by mattdotmac** [comment]
I have same issue as @GuyKahlon. News notifications don't work even when they are turned on in the settings app, and the app has to be reloaded in to memory in order for the new news item to appear. 

I am only able to see a new message: 
- if I switch to another contact from the menu, then switch back
- if the app is reloaded

My subscription types are identical to Guy's.

I hope this is insightful!

**Comment by evermeer** [comment]
If you log in into the CloudKit dashboard, do you see (at the left bottom) the message: 'Reindexing development data'?

**Comment by mattdotmac** [comment]
Not currently, no. I recall possibly seeing that message at one point for maybe 30 seconds, but because I no longer can see it, I imagine that the development data has been fully indexed.

Hope this helps

**Comment by ehe969** [comment]
I want to know how did you solve the problem , I faced the same confused, Thank you ! @mattdotmac @GuyKahlon

**Comment by ehe969** [comment]
I have allow notification when alert show, but when i chat with another people, he clould't receive notificaion, when  he exit the app, and back app again,he will see the message  . This is why, can you help me, Thank    @@@you!

**Comment by PPacie** [comment]
The subscriptions are working fine for News/Messages. However, there is something missing in the **AppMessages** example app. 

You need to call `application.registerForRemoteNotifications()` in the `application:didFinishLaunchingWithOptions` method of the App Delegate.

**Comment by evermeer** [comment]
strange... I do mention it in the readme.md but it's gone from the AppDelegate in the demo. Thanks for finding this. I will fix it now.

**Comment by evermeer** [comment]
It's fixed and pushed as version 3.1.0
