### ISSUE TITLE
"Network Failure" (4/1013); "Fetching asset failed"

### ISSUE THREAD

**Issue by misuqian** [evermeer/EVCloudKitDao#58]
Have any solution?
```
EVCloudKitDao.publicDB.getItem(messa.asset_id, completionHandler: { result in
                let asset = result as! Asset
                if let image = asset.image(){
                    ImageStore(image,imageName: messa.assetName)
                }
                }, errorHandler: {error in
                    print("photo \(error)")
            })
```

**Comment by misuqian** [comment]
http://stackoverflow.com/questions/28356585/cloudkit-fetchrecordwithid-error-fetching-asset-failed
WOW!!

**Comment by evermeer** [comment]
😜That's cool indeed!
So is your question awnsered?

**Comment by misuqian** [comment]
No really,I try to suggest user to use wifi or 4G

**Comment by evermeer** [comment]
There is also a Gitter channel for EVCloudKitDao. So If you have any questions, just ask them.
See https://gitter.im/evermeer/EVCloudKitDao?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
