### ISSUE TITLE
Obj names are changing to "_" 

### ISSUE THREAD

**Issue by rahimizad** [evermeer/EVCloudKitDao#62]
Hi, do you know why all variables of the class are changing as follows with the "_" ?

(lldb) po dict
▿ 10 elements
  ▿ [0] : 2 elements
    - .0 : location
  ▿ [1] : 2 elements
    - .0 : location_name
    - .1 : 🏢 Bonny Slope
  ▿ [2] : 2 elements
    - .0 : record_type
  ▿ [3] : 2 elements
    - .0 : modification_date
    - .1 : 2016-05-01 03:37:41 +0000
  ▿ [4] : 2 elements
    - .0 : last_modified_user_record_i_d
  ▿ [5] : 2 elements
    - .0 : creation_date
    - .1 : 2016-05-01 03:37:41 +0000
  ▿ [6] : 2 elements
    - .0 : creator_user_record_i_d
  ▿ [7] : 2 elements
    - .0 : encoded_system_fields
  ▿ [8] : 2 elements
    - .0 : record_change_tag
  ▿ [9] : 2 elements
    - .0 : record_i_d

`    /**
     Put a dictionary recursively in a CKRecord
     
     - parameter record: the record
     - parameter dict:   the dictionary
     - parameter root:   used for expanding the property name
     */
    private func dictToCKRecord(record: CKRecord, dict: NSDictionary, root:String = "") {
        for (key, value) in dict {
            
            guard let key: String = key as! String  else { continue }
            
            if !(["record_i_d", "recordID", "recordType", "creationDate", "creatorUserRecordID", "modificationDate", "lastModifiedUserRecordID", "recordChangeTag", "encodedSystemFields"]).contains(key) {
                if value is NSNull {
                    // record.setValue(nil, forKey: key) // Swift can not set a value on a nulable type.
                } else if let dict = value as? NSDictionary {
                    dictToCKRecord(record, dict: dict, root: "\(root)\(key)__")
                } else if key != "recordID" {
                    record.setValue(value, forKey: "\(root)\(key)")
                }
            }
        }
    }`

class PublicLocation: EVCloudKitDataObject {
    
    var location = CLLocation()
    var locationName = ""

It's converting my locationName to location_name when it saves it to cloudkit!

**Comment by evermeer** [comment]
With EVReflection (which is used to map objects to and from dictionaries) the default option is set to KeyCleanup. Besides automatic conversion of swift keywords it will also handle conversion between pascal case and snake case. In this case all fields are converted to snake case (all lower case and underscore between words) In previous versions this conversion was enforced when going from a dictionary to an object but in the latest version it was also done when going from an object to a dictionary. It's easy to override this default. I will have a look at it now.

**Comment by evermeer** [comment]
key cleanup has now been disabled in version 2.20.0
