### ISSUE TITLE
Save while offline

### ISSUE THREAD

**Issue by kimdv** [evermeer/EVCloudKitDao#67]
Hello! 

I was wondering if i could save something while i'm offline, and then later upload it to the cloud?

If save something while i'm offline, it will show in the list, but when i get online it will delete the item and not save it to the cloud?

I just use the default saving method. 

//Kim

**Comment by evermeer** [comment]
When you are offline the save method will fail and call the errorHandler. You could then store the object somewhere else (disk) instead. You could use the .saveToTemp("yourTempFilename") on the object and then try to save the object later to CloudKit. You have to implement this retry mechanism yourself.
