### ISSUE TITLE
EVCloudData init method freezes

### ISSUE THREAD

**Issue by TrueGuy** [evermeer/EVCloudKitDao#69]
Hello!  
Thanks for great lib. I'm using Xcode 8, iOS 10 and discovered some weird behaviour when trying to access EVCloudData.publicDB singleton. It just hangs...  
So here is an example:  
![image](https://cloud.githubusercontent.com/assets/1129837/19419932/10e771d0-93ea-11e6-9140-268a0d1da65d.png)  
I tried to see why it is hanging and discovered that init method contents is never called:  
![image](https://cloud.githubusercontent.com/assets/1129837/19419961/8973ca68-93ea-11e6-87f3-86724f5ca932.png)  

and  

![image](https://cloud.githubusercontent.com/assets/1129837/19419963/a0635950-93ea-11e6-89b2-766bb15fb9a0.png)  

I dont see any problem with code. Do you know why this doesnt work?

**Comment by evermeer** [comment]
I can't reproduce this. The text 'this never happens' and 'cant see this line in console' will just be in my output.

**Comment by evermeer** [comment]
Please let me know if this still happens.

**Comment by GeorgeFedoseev** [comment]
seems like it was an issue with old Swift version or Xcode
