### ISSUE TITLE
Download of CKAsset content

### ISSUE THREAD

**Issue by sumowesley** [evermeer/EVCloudKitDao#73]
Hi there. I see from #17 that the .connect request should bring the record down to the local cache and save the CKAsset contents to local storage.

I have a Media recordtype in which I have a record per image file. The attached shows the CloudKit image with a size of 1060 bytes:
![evcloudkitdao_ck_mediafile](https://cloud.githubusercontent.com/assets/5694619/21699439/a3a1b088-d393-11e6-8e2d-4d6d7accc5ce.jpg)
I make my .connect request to my media files and then loop round them. I store a date when I last checked the media files and if the file is newer, I intend to copy it to the name stored within the media record. In this way i will save all the media files into the a media directory and can then let the app access all my image sizes e.g. normal, @2x and @3x without having to worry about that myself.

My problem is, that when I get my results of the .connect returned to me, it doesn't seem to download the CKAsset portion. The below image shows the contents of the CKAsset object for the same record as above and you can see that the size matches and it says that it isn't downloaded.
![evcloudkitdao_debug_mediafile](https://cloud.githubusercontent.com/assets/5694619/21699572/52d241e4-d394-11e6-8522-b596c5b2666c.jpg)

I want to loop through the images to extract newer items but alas, trying to read the contents of the CKAsset's fileURL leads to a nil value. Here is my loop code which is run as part of the completionHandler for the .connect request for my media records:

```
for m : Media in results {
    // using SwiftDate for .isBefore function
    if lastChecked.isBefore(date: m.MediaDate, orEqual: false, granularity: .minute) {

        let url = m.MediaFile!.fileURL
        let mediaData = NSData(contentsOfFile: url.absoluteString)       
 
        if (mediaData != nil) {
           // code to save document to file name and location of my choice goes here
        }
   
    }
}
```

Printing description of m.MediaFile.some._fileURL:
```
file:///private/var/mobile/Containers/Data/Application/40FFA9AA-784F-424A-9CE7-4F476CF2E040/Library/Caches/CloudKit/3916c9a30ee6a64429fc5f0daad374a96af17a0d/Assets/6700483D-0401-487D-96A7-BA24049CD46F.0182fc5afe8bdadc5aac7c72af5b93d33df6e81486
```

I have tried getting the record using .getItem and I have the same issue.

Is there something else I need to be doing to force the download of this document from CloudKit as part of my .connect request or is this a lifecycle thing e.g. am I too early with my request for the file or too late?

Xcode 8.2.1, ios devices at 10.2, macOS at 10.12.2

**Comment by evermeer** [comment]
Downloading the CKAsset and storing it to your application cache is done by CloudKit itself. It's not EVCloudKitDao functionality. I have never seen before that I got a record back from CloudKit and the asset itself was not at the location of the url. The files are stored in a cache. This means that they will be there for a longer period, but how long is unknown. Doing the copy to your media folder is a good thing to do. Then you know for sure that the asset is available also after a restart of your app.

The code that I am using to access asets is a little different. I am using Data instead of NSData and I don't parse it to .absoluteString. You should be able to get the file like this:
```
        if let file = m.MediaFile {
            if let data = try? Data(contentsOf: file.fileURL) {
                // Code to save the file
            }
        }
```

CloudKit is giving you an url... The asset should be there... You could try running the app in the simulator and then opening the url in finder to see if it's there.

**Comment by sumowesley** [comment]
Thank you for the response and your code which was much more elegant then mind.

This is more about lifecycle I fear. The presence of the record containing the CKAsset does not guarantee the asset itself is available. That happens separately. Having waited for a few seconds in the debugger, the files seemed to arrive. I will change my code to do the existing loop and create an array of files to be processed based on lastUpdate and availability of the file. I can then send the array off to a separate method that checks for the files that should be updated and copy them over to my media directory when they have been downloaded.

**Comment by sumowesley** [comment]
The theory was sound but the execution less so. You don't get access to the downloaded flag on CKAsset. I suspect only way is to try and check for the existence of the file or to try and get the data from it and repeat if file was not available. Feels ugly.

**Comment by sumowesley** [comment]
Does seem to be the on the second pass of the completionHandler that the file seem to be available and nothing to do with me waiting in the debugger. EVCloudKitDao working fine.

**Comment by evermeer** [comment]
This is all that the CKAsset documentations says about the availability of the file:

> When you download a record containing an asset, CloudKit keeps the asset data around for a little while but may delete it at any point in the future to free up disk space. After fetching a record containing an asset, you can retrieve the asset data with the URL in the fileURL property. If you want to ensure that the asset’s data remains local to the device, write the data to a file in your app’s local container directory and reference the data from the new file.

I also have never seen the behaviour described by you before. I have a messaging app that is capable of sending and receiving files (images). I never had the problem that an asset arrived but could not be accessed.

**Comment by sumowesley** [comment]
The completion handler certainly fires twice and they seem to be about on the second pass (make sense, query to CloudKit, not cached, described by you in #17) but their lifecycle locally seems a little unpredictable. If what I'm seeing is maintained I will be fine - I only want to download the new/changed images at the start of the session anyway.

Thank you for the help. It is much appreciated.
