### ISSUE TITLE
Swift 3?

### ISSUE THREAD

**Issue by endresjd** [evermeer/EVCloudKitDao#74]
Will this be updated to work with Swift 3?  I kinda assumed that this would be enough:

pod "EVCloudKitDao", :git => 'https://github.com/evermeer/EVCloudKitDao.git', :branch => 'Swift3'

Xcode will wants to convert both frameworks, this one and EVReflection.

**Comment by evermeer** [comment]
A, I will remove the Swift3 branch, that is the old branch that was merged to master. 
The master branch has an up to date Swift 3 version.

**Comment by evermeer** [comment]
Done, now just use:

`pod "EVCloudKitDao"`

**Comment by endresjd** [comment]
I think it really came down to a really out of date cocoapods installation on this machine.  Annoying on my part.

Thanks for the quick help!
