### ISSUE TITLE
Issue building AppMessage

### ISSUE THREAD

**Issue by endresjd** [evermeer/EVCloudKitDao#75]
If DEBUG is defined, then main.m results in:

fatal error: '/tmp/injectionforxcode/BundleInjection.h' file not found
#import "/tmp/injectionforxcode/BundleInjection.h"

Maybe because of new Xcode?

**Comment by evermeer** [comment]
Ah no sorry, I have been playing with injection for xcode.
That's a tool that you can use for injecting code in a running app.
You can fix it by making the entire main.m empty.
I will now makt that update and push it to GitHub

**Comment by evermeer** [comment]
done.
