### ISSUE TITLE
Any plan for Swift 3 support?

### ISSUE THREAD

**Issue by superarts** [evermeer/EVCloudKitDao#76]

**Comment by evermeer** [comment]
The master branch is alteady Swift 3 for a couple of months. Could you try doing a pod update to see If you get the latest version?

**Comment by superarts** [comment]
Sorry didn't realize that Swift 3 support is not pushed to `cocoapods`. The following line worked for me.

`pod "EVCloudKitDao", :git => 'https://github.com/evermeer/EVCloudKitDao.git', :branch => 'master'`

**Comment by evermeer** [comment]
Hmm also Cocoapods should have given you the latest swift 3 version. I will do Some tests later. I'm now for 4 days in the UK for a short vacation.

**Comment by superarts** [comment]
Thanks, in this case I shall reopen the task and please take a look at it later when you're back. Enjoy your vocation!

**Comment by evermeer** [comment]
I'm not able to reproduce this issue. I will get the latest swift 3 version every time. Could it be that your local cocoapods database was out of sync? a `pod cache clean` might help.

**Comment by superarts** [comment]
Thanks, I can confirm that it works for me in `Xcode 8.3.1` with `Swift 3.1` with some `Swift 3.1` related warnings.

**Comment by evermeer** [comment]
I just published version 3.3.3 with a fix for the swift 3.1 warnings
