### ISSUE TITLE
Can't list all item in a "Table"

### ISSUE THREAD

**Issue by taiyoOzora** [evermeer/EVCloudKitDao#79]
Hi,
Still new to this sorry if it's not really an issue. I've been using this code
`EVCloudKitDao.privateDB.query(Note(), orderBy: OrderBy(field: "title", parent: nil, direction: .ascending), completionHandler: {results, success in
  self.notes = results
  Async.main({self.tableView.reloadData();})
  return success
})`
and it's was working fine until i recently start using it again and it doesn't seem to query anything.

I recently changed the dashboard from development to production as when I uploaded to testflight (Mayb the cause of the problem, I'm not sure) I can't seem to get any results (works when I build with xcode not testflight) but now both doesn't work.

If its possible could you help me on both the issue as I can't really seem to solve it.

**Comment by evermeer** [comment]
When you move a database to production, then only the table definition is moved. No data will be migrated to production. You have to create the data again.

**Comment by taiyoOzora** [comment]
I've done that and received a success reply however when i query the data with the code it returns me an error `EVCloudKitDao.swift(227) handleCallback(_:errorHandler:completionHandler:):
	Error: Optional(12) = Optional("Field \'___recordID\' is not marked queryable")`

**Comment by evermeer** [comment]
Like the error is already telling you, you should make the field recordID queryable. You can do that in the dashboard. You have to specify that for each field that you want to query for. 

<img width="1603" alt="screen shot 2017-04-24 at 07 34 32" src="https://cloud.githubusercontent.com/assets/130834/25323582/884b5726-28c0-11e7-86c2-dbec7474fd78.png">

**Comment by taiyoOzora** [comment]
Thanks it seems to work on the development side but I can't seem to create record types in production.
`EVCloudKitDao.privateDB.createRecordTypes([Note(), Asset()])` 

I tried `com.apple.developer.icloud-container-environment` to Production seems to connect to the cloudkit in production mode but cannot create record type in there. Seems like I cannot manually create the recordType either

**Comment by evermeer** [comment]
Ah! You are not allowed to create record types on production. You can only create record types on dev and they will be created on production when you migrate to production. It's a CloudKit limitation.

**Comment by taiyoOzora** [comment]
Okay thanks. That means I can't really test much with testflight until i'm done programming... that sux ><

**Comment by evermeer** [comment]
Well... You should always first test on development. Doing that would create the recordTypes. You only have to remember to move to production in the CloudKit dashboard before distributing with TestFlight.
