### ISSUE TITLE
Re: EVCloudData.connect method

### ISSUE THREAD

**Issue by yoonack** [evermeer/EVCloudKitDao#8]
Hi, I just found a problem with the EVCloudData.connect method, I called initializeConnection() method in the viewDidAppear() function, then in deinit I called disconnect method. However, when I switch back to another view and come back, it will call viewDidAppear again and called EVCloudData.connect first, then it will call the deinit of the previous view to disconnect, this would cause the EVCloudData.publicDB.data[filterID] filed to be nil which causes error when loading data in the tableview.

I wonder if calling disconnect is necessary? otherwise I have to manually check when to call the disconnect method in order to prevent the crash.

**Comment by evermeer** [comment]
the deinit is called when the viewController is thrown away. The instance will be gone. The .connect code is part of the viewController. The connection can not be kept alive. This is why the deinit should always disconnect. If you want to keep the data alive between screen switches, then you could implement the .connect in the calling view controller (your menu or rootview controller)

It sounds like you have 2 identical .connect methods (with the same filterID) Then indeed the 2 will influence each other. It would be better to just put 1 connect in the controller that initiate both controllers. You can see a sample of that in the test project. See the connectToNews in LeftMenuViewController. An other workaround would be to use a seperate filterID

**Comment by yoonack** [comment]
Thank you for the help. Yeah, I created a connection whenever one of the UITapBarView is appeared, when I switch back to root tableview and comeback, it will create another instance of the UITapBarView and then calls the deinit of the previous UITapBarView. This would cause the unexpected nil value found. I am calling .connect method to get information specifically to that table row, so if I pass the UITapBarView different information, it will get different data. However, if I keep switching, the same information is passed to UITapBarView, it will try connecting the same data. I need to think about a way to avoid the unexpected found nil value. Thanks for the help.

**Comment by evermeer** [comment]
If you need any more help, then just let me know.
