### ISSUE TITLE
Is it required always to disconnect from public database in VC deinit()?

### ISSUE THREAD

**Issue by gtennis** [evermeer/EVCloudKitDao#81]
If public db tables are used for storing global/common/shared data, why do we need to disonnect from the public's db table in each VC's deinit()? Wouldn't it clear up cached public records? The only reason I can think of is the next time the same view controller will be created and connect to table called, it wont pick the previous connection and will pull all the table records again while still keeping both connections. The reason I'm asking is I want all my data operations encapsulate inside DataManager instance will live while the app is running.

**Comment by evermeer** [comment]
If you don't disconnect, then a reference to your callback function will remain active. These could then be called when for instance a push notification arrives. If you did not use a weak self, then it could even cause a crash. Performing a disconnect is advised. When you are using a DataManager to handle the .conect then you could put the .disconnect in the deinit of that DataMAnager.

**Comment by gtennis** [comment]
Thanks!
