### ISSUE TITLE
How to update an item? - Should update documentation...

### ISSUE THREAD

**Issue by gtennis** [evermeer/EVCloudKitDao#82]
Is it possible to update an item? I'm trying to use the same "saveItem" method for both insert and update by passing already fetched MyCKDataObject with modified properties, but that creates a new item.

**Comment by gtennis** [comment]
Sorry, it's was my mistake. Everything works as it should be.

**Comment by gtennis** [comment]
I would be awesome if there would be an example in AppMessage demo project or somewhere in documentation with an example how to perform all CRUD operations. I checked EVCloudKitDao, the documentation and Google but could not find examples just to check if it's my mistake or it's not supported... yet.

**Comment by evermeer** [comment]
True... The documentation could be better...
