### ISSUE TITLE
Any thoughts for RealmSwift offline db integration?

### ISSUE THREAD

**Issue by gtennis** [evermeer/EVCloudKitDao#83]
Just a question - any thoughts for RealmSwift offline DB integration?

**Comment by evermeer** [comment]
EVCloudKitDao is based on EVReflection which has support for realm. See https://github.com/evermeer/EVReflection/tree/master/Source/Realm
But when you also want to support Realm plus CloudKit, then your base object has to derive from the Realm Object. 

You could achieve that. For that you have to make a copy of the CKDataObject That is in EVReflection and instead of using EVObject as it's base class you should use Realms Object and also implement the EVReflectable protocol. So your definition will be:

`open class MySuperDataObject: Object, EVReflectable {`
 
Then also add all code that is inside EVObject into your CKDataObject

**Comment by evermeer** [comment]
But... Why use realm if you can already just write all data to a file? EVCloudData already has a caching mechanism that does that.

**Comment by gtennis** [comment]
Thanks for the suggestions. Well, I'm considering Realm because it gives offline storage. As far as I understood from your reply, as soon as EVCloudData object is retrieved from CloudKit, it's cached and such caching is done automatically. That's awesome, but is there a workaround how to allow to store / write-to-cache a new object (is no internet) which will be send to CloudKit next time internet is on?

**Comment by evermeer** [comment]
EVCloudKit does not have a mechanism for caching updates. When you save an object and there is a problem with the connection, then you will get an error. you should handle this yourself. The easiest would be by adding the object to a persistent queue and when the internet connection is back you should process that queue.

**Comment by gtennis** [comment]
Persistent queue...very interesting suggestion. I understand we are trying to find a workaround simulating offline behaviour, but it's interesting to understand how far I can go with this persistent queue approach. Let's say, there are two methods:

* dataManager.addItem 
* dataManager.getItemList

Lets say a user adds new item while being offline and this object is stored in persistent queue. However, dataManager.getItemList won't return this new "added" new item, unless it will check and merge (distinct) items both from persistent queue and cache. Also, things could get more complext if user adds, then updates, and removes while being offline and so dataManager.getItemList should take into consideration different object versions and should check what objects need to be returned. 

However, it's very interesting approach. I will think about it, thanks!

**Comment by evermeer** [comment]
The .connect is the core of EVCloudData. It will return cached data if it's there, execute the query and create a subscription. Data returned from the query will always be written to a cache. When you do an insert, delete or update, then always first the cache will be updated. These updates could also trigger events in the various .conect's you have **active**. 

So when there is a connection error while you do an update, the lists you have in place will show you the updated data. You only have to make sure that you perform the update again now or later (using a persistent queue). Of course when a .connect is not active yet and you execute it after the failed update, then it will not include the updates.

I think for making this part of EVCloudData the following things has to be added (make it optional?):
- When an update fails, the updated object will be added to a queue (how to handle deletes?)
- when a connect is executed then right before returning the cache or result the queue will be processed on the data. (see the upsert function which already does that)
- A (timed) processing mechanism that will retry updates that are in the queue.

As you can see EVCloudData is not very complex. Adding the above logic is very doable. Unfortunately it's still too much for me to work on this in the near future. Of course a pull request with some of this logic would be very welcome.

**Comment by gtennis** [comment]
Sorry for the delay. Thanks for the excellent suggestions! I will let you know if I managed to create any useful implementation which is worth sharing.
