### ISSUE TITLE
modify existing record failed

### ISSUE THREAD

**Issue by foolbear** [evermeer/EVCloudKitDao#87]
insert new book or increase reader count if the book already exists.

17-09-19 16:30:29 CKManager[164], saveBookFSC(_:_:completion:): save CKBookFS error: Error saving record <CKRecordID: 0x1039b95f0; recordName=3A42AEB9-2D28-45D4-A9C1-2CABC6E1078A, zoneID=_defaultZone:__defaultOwner__> to server: WRITE operation not permitted

```
	func saveBookFSC(_ bookFS: BookFS, _ ckBook: CKBook, completion: @escaping (_ ckBookFS: CKBookFS?) -> Void) {
		EVCloudKitDao.publicDB.query(CKBookFS(), predicate: NSPredicate(format: "url == %@", bookFS.url), completionHandler: { results, _ in
			var cKBookFS = CKBookFS()
			if results.count > 0 {
				cKBookFS = results[0]
				cKBookFS.readerCount += 1
			} else {
				cKBookFS.url = bookFS.url
				cKBookFS.imageUrl = bookFS.image_url
				cKBookFS.introduction = bookFS.introduction
				cKBookFS.readerCount = 1
				cKBookFS.putBook(ckBook.recordID.recordName)
			}
			EVCloudData.publicDB.saveItem(cKBookFS, completionHandler: { cKBookFS in
				completion(cKBookFS)
			}, errorHandler: { error in
				completion(nil)
				foolPrint("save CKBookFS error: \(error.localizedDescription)")
			})
			return false
		}, errorHandler: { error in
			completion(nil)
			foolPrint("query CKBookFS error: \(error.localizedDescription)")
		})
	}
```

**Comment by evermeer** [comment]
You probably need to set permission to allow a user to write (or delete) a record created by someone else. You do that in the Development Environment, under Schema, Record Types, select the specific record, then over on the right there is a drop down menu labelled Security. Grant to the Role ' Authenticated' the right to Read and Write. Then deploy to Production.

**Comment by foolbear** [comment]
copy that, thanks
