### ISSUE TITLE
how to handle error: "is not key value coding-compliant for the key"

### ISSUE THREAD

**Issue by foolbear** [evermeer/EVCloudKitDao#88]
🌀 
WARNING: The class 'CKBook' is not key value coding-compliant for the key 'title'
 There is no support for optional type, array of optionals or enum properties.
As a workaround you can implement the function 'setValue forUndefinedKey' for this. See the unit tests for more information

🌀 
WARNING: The class 'CKBook' is not key value coding-compliant for the key 'author'
 There is no support for optional type, array of optionals or enum properties.
As a workaround you can implement the function 'setValue forUndefinedKey' for this. See the unit tests for more information

> class CKBook: CKDataObject {
> 	var title: String = ""
> 	var author: String = ""
> }

**Comment by evermeer** [comment]
Does your CKBook object have a property with the name author?
Is it a String or optional String or is it a sub object?

Or did you just upgrade to Swift 4?
If so, then you need the Swift 4 branch of EVReflection.
You could also make the change manually.
There is only 1 line that should be added to EVObject
The line `@objcMembers`should be added right before the class definition like this:

```
@objcMembers  
open class EVObject: NSObject, NSCoding, EVReflectable  {
```

**Comment by foolbear** [comment]
wonderful, it works for Swift 4, thanks!

and some warnings in Reflection and EVCloudKitDao:
EVReflection.swift:1334:35: 'substring(to:)' is deprecated: Please use String slicing subscript with a 'partial range upto' operator.
EVCloudKitDao.swift:830:32: 'init(recordType:predicate:subscriptionID:options:)' was deprecated in iOS 10.0: Use CKQuerySubscription instead
EVCloudKitDao.swift:851:68: 'predicate' was deprecated in iOS 10.0: Use CKQuerySubscription instead

**Comment by evermeer** [comment]
Thanks! I will have a look at it this weekend.
