### ISSUE TITLE
deprecated on Swift4

### ISSUE THREAD

**Issue by foolbear** [evermeer/EVCloudKitDao#92]
1. Utilities/EVCloudKitDao/EVCloudKitDao.swift:830:32: 'init(recordType:predicate:subscriptionID:options:)' was deprecated in iOS 10.0: Use CKQuerySubscription instead

2. Utilities/EVCloudKitDao/EVCloudKitDao.swift:851:68: 'predicate' was deprecated in iOS 10.0: Use CKQuerySubscription instead

3. AppDelegate.swift:30:48: 'UIUserNotificationSettings' was deprecated in iOS 10.0: Use UserNotifications Framework's UNNotificationSettings

4. AppDelegate.swift:30:15: 'registerUserNotificationSettings' was deprecated in iOS 10.0: Use UserNotifications Framework's -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:] and -[UNUserNotificationCenter setNotificationCategories:]

5. Utilities/EVCloudKitDao/EVReflection.swift:1334:35: 'substring(to:)' is deprecated: Please use String slicing subscript with a 'partial range upto' operator.

**Comment by foolbear** [comment]
/Users/foolbear/Jobs/Reading/Reading/AppDelegate.swift:30:15: 'registerUserNotificationSettings' was deprecated in iOS 10.0: Use UserNotifications Framework's -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:] and -[UNUserNotificationCenter setNotificationCategories:]

**Comment by foolbear** [comment]
/Users/foolbear/Jobs/Reading/Reading/Utilities/EVCloudKitDao/EVCloudKitDao.swift:830:32: 'init(recordType:predicate:subscriptionID:options:)' was deprecated in iOS 10.0: Use CKQuerySubscription instead

**Comment by foolbear** [comment]
Utilities/EVCloudKitDao/EVCloudKitDao.swift:851:68: 'predicate' was deprecated in iOS 10.0: Use CKQuerySubscription instead

**Comment by foolbear** [comment]
1. Utilities/EVCloudKitDao/EVCloudKitDao.swift:830:32: 'init(recordType:predicate:subscriptionID:options:)' was deprecated in iOS 10.0: Use CKQuerySubscription instead

2. Utilities/EVCloudKitDao/EVCloudKitDao.swift:851:68: 'predicate' was deprecated in iOS 10.0: Use CKQuerySubscription instead

3. AppDelegate.swift:30:48: 'UIUserNotificationSettings' was deprecated in iOS 10.0: Use UserNotifications Framework's UNNotificationSettings

4. AppDelegate.swift:30:15: 'registerUserNotificationSettings' was deprecated in iOS 10.0: Use UserNotifications Framework's -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:] and -[UNUserNotificationCenter setNotificationCategories:]

**Comment by evermeer** [comment]
I'm first working on making EVReflection work well with Swift 4.

**Comment by foolbear** [comment]
thanks

**Comment by MortenGregersen** [comment]
I've created a pull request for this #100

**Comment by evermeer** [comment]
🎉  YAY
🚀  EVCloudKitDao (3.5.1) successfully published

Thanks @MortenGregersen
