### ISSUE TITLE
How can I get user's Information：first/last name and avatar, user reference from users table

### ISSUE THREAD

**Issue by foolbear** [evermeer/EVCloudKitDao#94]

**Comment by evermeer** [comment]
When you use CloudKit getting user information is limited 

In EVCloudKitDao you can get information about yourself using `EVCloudKitDao.publicDB.discoverUserInfo`

For getting your contacts you can use the function `EVCloudKitDao.publicDB.allContactsUserInfo` 

Depending on the OS version this will return either CKDiscoverUserInfo or CKUserIdentity
CKDiscoverUserInfo is pre iOS 10 and will only return first and last name.
For the other see https://developer.apple.com/documentation/cloudkit/ckuseridentity

**Comment by foolbear** [comment]
Using same App(public db), user A rate the Book, user B rate the same book, then user C show the ratings for this book. Can names of A/B will be obtained in App of user C?

And what do contacts means? using same app?

**Comment by evermeer** [comment]
the allContactsUserInfo will give you a list of all your device contacts that also have the same app installed. Of course you will be asked if the app is allowed to query your contacts. If you want user information for other users than what's in your contacts, then you have to create your own mechanism for that. The best thing would be to execute the EVCloudKitDao.publicDB.discoverUserInfo on startup and then store the data in your own table (not in the Users table because that's a system table with limitations) You could then perform whatever query you like. Of course in your case you would also want to save an ID to the user record in the table where you save ratings.

**Comment by foolbear** [comment]
I found in your sample code that load all contacts info from beginning, then append user name info into custom fields(FromFirstName,FromLastName) when send msg. is it possible get user info from From_ID or From?

in my case, can i get user name from readerId or reader?

```
class CKRate: CKDataObject {
	var rate: Int = 0
	var comment: String = ""
	
	var readerId: String = ""
	var reader: CKReference?
	func putReader(_ id: String) {
		self.readerId = id
		self.reader = CKReference(recordID: CKRecordID(recordName: id), action: .deleteSelf)
	}
	
	var bookFSId: String = ""
	var bookFS: CKReference?
	func putBookFS(_ id: String) {
		self.bookFSId = id
		self.bookFS = CKReference(recordID: CKRecordID(recordName: id), action: .deleteSelf)
	}
}
```

**Comment by evermeer** [comment]
In CloucKit you can only get information about yourself and information about your contacts' If you want more, then you need to create your own UserInfo table and make sure it's populated with the user data. Then you could create a reference to that UserInfo table from whatever data you like. And if you have that reference, you can read the record from your UserInfo and display that data.

**Comment by foolbear** [comment]
I mean how can i get contact's info from CKRate.reader which is reference from system table Users.

**Comment by evermeer** [comment]
You can then get the record directly using it's ID using something like:

```
 EVCloudKitDao.publicDB.getItem(rate.bookFSId
            , completionHandler: { item in

            }, errorHandler: { error in

        })
```
And as I said... You can not use the Users table. There are limitations on it. For instance you can't query it. So you need to create your own table with user data. Just use `EVCloudKitDao.publicDB.discoverUserInfo` and save the result in your own user table

**Comment by foolbear** [comment]
you mean use EVCloudKitDao.publicDB.getItem(readerId）to get CKUserIdentity item, then user name?

**Comment by foolbear** [comment]
can i get contact's info using discoverUserIdentity?

**Comment by evermeer** [comment]
You will get your own contact info.

**Comment by foolbear** [comment]
allContactsUserInfo always return one time: self, why? the same for your demo appmessage.
1. both iphone(latest ios11) with differents icloud accounts
2. running the same appmessage
3. icould for appmessage enabled on both phone.
4. no any item in settings-icloud-find me

**Comment by evermeer** [comment]
It should return a list of contact that also have the same app installed. So if you only get 1 contact back, then that would mean that only that contact has the app installed. For more information see the Apple CloudKit documentation for discoverAllUserIdentitiesCompletionBlock
