### ISSUE TITLE
Which thread does completionHandler working in for query/save/connect?

### ISSUE THREAD

**Issue by foolbear** [evermeer/EVCloudKitDao#95]

**Comment by foolbear** [comment]
and query/save/connect must be invoke from main thread?

**Comment by evermeer** [comment]
queries are always performed on a background thread (default CloudKit behaviour). To make things easier the connect in EVCloudKitData will perform all callbacks on the main thread (since you probably often want to update the UI). For EVCloudKitDao all callbacks are still performed on a background thread.

**Comment by foolbear** [comment]
these are 2 questions:
1. operations invoke
2. operations completionHandler running in

about 3 operations:
1. query
2. saveItem??
3. connect

for example:

rate a book, we will found cKBook

```
// must be invoked in main thread?
func getOrNewBookFSForReadC(_ bookFS: BookFS, _ ckBook: CKBook, completion_: @escaping (CKBookFS?) -> Void) {
		EVCloudKitDao.publicDB.query(CKBookFS(), predicate: NSPredicate(format: "url == %@", bookFS.url), completionHandler: { results, _ in 
// in background thread 1
			var cKBookFS = CKBookFS()
			if results.count > 0 {
				cKBookFS = results[0]
				cKBookFS.readerCount += 1
			} else {
				cKBookFS.url = bookFS.url
				cKBookFS.imageUrl = bookFS.image_url
				cKBookFS.introduction = bookFS.introduction
				cKBookFS.readerCount = 1
				cKBookFS.putBook(ckBook.recordID.recordName)
			}

                        // it's ok invoked in background thread
			EVCloudData.publicDB.saveItem(cKBookFS, completionHandler: { cKBookFS in 
// in background thread 2 or main thread?
				completion_(cKBookFS)
			}, errorHandler: { error in
				completion_(nil)
				foolPrint("save CKBookFS error: \(error.localizedDescription)")
			})
			return false
		}, errorHandler: { error in
// main or background thread?
			completion_(nil)
			foolPrint("query CKBookFS error: \(error.localizedDescription)")
		})
	}
```

**Comment by evermeer** [comment]
Summarised this is how threading is handled:
- All functions can be executed on both the main thread or any background thread
- All CloudKit opperations will be executed on a background thread (for both EVCloudKitDao and EVCloudKitData) So the function will return immediately while the action is processed on an other thread.
- All Callbacks from EVCloudKitDao will be executed on a background thread
- All Callbacks from EVCloudKitData will be executed on the main thread

**Comment by foolbear** [comment]
Thanks, it's clear.
