### ISSUE TITLE
appstore reject for requestDiscoverabilityPermission

### ISSUE THREAD

**Issue by foolbear** [evermeer/EVCloudKitDao#99]
Your app accesses uses’ emails from the device but does not have the required precautions in place. It would be appropriate to revise the modal alert so that users understand how this app uploads their emails to the server.

**Comment by evermeer** [comment]
Like any other permission you need to request it.
I can advice using https://github.com/ennioma/arek
It has support for CloudKit

Apparently Apple wants you do do a little more than just showing a popup.

**Comment by foolbear** [comment]
OK，thanks
